"""Generate the critique log's index, because 91 entries with none is not a log.

`critique_log.md` is the designated long form of this project's reasoning: the
brief says `WEEKEND.md` is the five-minute version and this file and
`paper_draft.md` are where the working goes. It has reached 43,000 words across
91 numbered entries, appended newest-last, with no way to find anything. A
reader asking "why was the RPCA channel withdrawn" has to scan every heading.

The index is generated rather than maintained. A hand-maintained one is the
defect entry 90 found in the README: prose that stops matching the thing it
describes, with nothing to notice. It is written between markers so the log
stays append-only everywhere else.

    python scripts/critique_index.py             # rewrite the index in place
    python scripts/critique_index.py --check     # exit 1 if it is out of date
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

LOG = Path("critique_log.md")
BEGIN = "<!-- INDEX: generated by scripts/critique_index.py -->"
END = "<!-- END INDEX -->"
ENTRY = re.compile(r"^###\s+(\d+)\.\s+(.*?)\s*$", re.M)


def slug(text):
    """GitHub's heading anchor rule, close enough for this file."""
    s = text.lower()
    s = re.sub(r"[^\w\s-]", "", s)
    return re.sub(r"[\s_]+", "-", s).strip("-")


def build(text):
    rows = []
    for m in ENTRY.finditer(text):
        n, title = m.group(1), m.group(2)
        rows.append(f"- **{n}.** [{title}](#{slug(f'{n}. {title}')})")
    if not rows:
        return None
    body = "\n".join(rows)
    return (f"{BEGIN}\n\n<details>\n<summary><strong>{len(rows)} entries — "
            f"click to expand</strong></summary>\n\n{body}\n\n</details>\n\n"
            f"{END}")


def splice(text, block):
    if BEGIN in text and END in text:
        pre = text[:text.index(BEGIN)]
        post = text[text.index(END) + len(END):]
        return pre + block + post
    # first time: place it after the file's own preamble, before the first
    # session heading, so the log stays append-only below
    m = re.search(r"^---\s*$", text, re.M)
    at = m.end() if m else len(text.split("\n")[0])
    return text[:at] + "\n\n" + block + "\n" + text[at:]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    text = LOG.read_text()
    block = build(text)
    if block is None:
        print("no numbered entries found")
        return 0
    new = splice(text, block)
    n = len(ENTRY.findall(text))

    if a.check:
        if new != text:
            print(f"critique_log.md index is out of date ({n} entries). "
                  "Run `python scripts/critique_index.py`.")
            return 1
        print(f"index current, {n} entries")
        return 0

    LOG.write_text(new)
    print(f"indexed {n} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
