"""Regenerate paper_draft.md from runs/*.json. Prose lives here; numbers do not.

    python scripts/paper.py

Same contract as report.py: every figure in the output is computed from a run
in this repository at the moment the file is written. If a cell is missing the
draft says `[not measured]` rather than carrying a plausible number, and if a
whole section has no data behind it the section says so in place of a result.
"""
from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from wts.data import CLASSES                                    # noqa: E402

NM = "[not measured]"


def load(run_dir="runs"):
    cells = {}
    for p in sorted(Path(run_dir).glob("*.json")):
        r = json.loads(p.read_text())
        if isinstance(r, dict) and {"protocol", "encoder", "objective"} <= set(r):
            cells.setdefault((r["protocol"], r["encoder"], r["objective"],
                              r.get("tag", "")), {})[r.get("seed", 0)] = r
    return cells


def stat(cells, key, field=("test", "macro_f1")):
    v = cells.get(key)
    if not v:
        return None
    xs = []
    for r in v.values():
        x = r
        for f in field:
            x = x.get(f) if isinstance(x, dict) else None
            if x is None:
                break
        if x is not None:
            xs.append(float(x))
    if not xs:
        return None
    return {"mean": sum(xs) / len(xs), "hr": (max(xs) - min(xs)) / 2,
            "n": len(xs), "vals": sorted(xs)}


def fmt(s, n=4):
    if s is None:
        return NM
    if s["n"] == 1:
        return f"{s['mean']:.{n}f}"
    return f"{s['mean']:.{n}f} ±{s['hr']:.{n}f} (n={s['n']})"


def table(rows, header):
    out = ["| " + " | ".join(str(h) for h in header) + " |",
           "|" + "|".join(["---"] * len(header)) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


ENC = {"feat": "descriptors + MLP", "cnn_bn": "CNN (BatchNorm)",
       "cnn_gn": "CNN (GroupNorm)", "spectral": "spectral operator",
       "graph": "die-graph GNN", "rpca_cnn": "CNN + 4th channel"}
PROTOS = ["iid", "lot", "size", "lot_time"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", default="runs")
    ap.add_argument("--out", default="paper_draft.md")
    a = ap.parse_args()
    C = load(a.runs)
    L = []
    W = L.append

    W("# What actually shifts in wafer-map data, and why the "
      "domain-generalization toolbox does not help")
    W("")
    W("*Working draft. Regenerated by `scripts/paper.py`; every number is "
      "computed from a run in `runs/` when this file is written. A metric with "
      "no run behind it reads " + NM + ".*")
    W("")

    # ---------------------------------------------------------------- abstract
    lot = stat(C, ("lot", "cnn_gn", "erm", ""))
    iid = stat(C, ("iid", "cnn_gn", "erm", ""))
    lt = stat(C, ("lot_time", "cnn_gn", "erm", ""))
    sz = stat(C, ("size", "cnn_gn", "erm", ""))
    W("## Abstract")
    W("")
    W("Wafer-map defect classification is usually reported on a random split of "
      "WM-811K. We rebuild it as a domain-generalization benchmark on the same "
      "172,948 labelled wafers, 10,762 lots and 344 geometries, with four "
      "protocols that differ only in what is held out, and we find that the "
      "axis the literature worries about is not the expensive one. Holding out "
      "whole lots costs a GroupNorm CNN "
      f"{fmt(iid)} → {fmt(lot)} macro-F1; holding out *future* lots under a "
      f"purged, embargoed, forward-only split costs {fmt(lt)}. Nine borrowed "
      "invariance objectives fail to beat ERM — but we then show that on the "
      "lot protocol that finding is partly an artefact of how `domain` was "
      "defined in our own harness, so we withdraw it there and re-run it. Two "
      "methods we built for this corpus, an RPCA lot-signature channel and "
      "lot-adversarial self-supervised pretraining, do not survive their own "
      "controls: the first is matched by a channel of zeros, the second is "
      "worse than random initialization. We report seed spread throughout, "
      "because on one protocol it is larger than most published effects.")
    W("")

    # ---------------------------------------------------------------- protocols
    W("## 1. Four protocols over one corpus")
    W("")
    rows = []
    for p in PROTOS:
        any_cell = next((r for k, v in C.items() if k[0] == p
                         for r in v.values()), None)
        if not any_cell:
            rows.append([f"`{p}`", NM, NM, NM, NM]); continue
        rows.append([f"`{p}`", f"{any_cell['label_shift_tv']:.4f}",
                     f"{any_cell['n_train']:,}", f"{any_cell['n_val']:,}",
                     f"{any_cell['n_test']:,}"])
    W(table(rows, ["protocol", "label shift (TV)", "train", "val (OOD)", "test"]))
    W("")
    W("`iid` shuffles wafers. `lot` holds out whole lots. `size` holds out whole "
      "wafer geometries. `lot_time` sorts lots by production order, trains on "
      "the earliest, embargoes a band, and tests on the latest — the split a "
      "backtest uses, because deployment only runs forwards. Holding out groups "
      "cannot hold the label marginal fixed, so the induced label shift is "
      "measured rather than assumed away; `lot_time` carries the largest.")
    W("")
    W("Model selection for every cell uses a validation split carved from the "
      "*training* domains, never the test domains.")
    W("")

    # ---------------------------------------------------------------- result 1
    W("## 2. Result: lot holdout is cheap, forward-only time is expensive")
    W("")
    rows = []
    for e in ENC:
        r = [ENC[e]] + [fmt(stat(C, (p, e, "erm", ""))) for p in PROTOS]
        if all(x == NM for x in r[1:]):
            continue
        gap = stat(C, ("iid", e, "erm", "")), stat(C, ("lot", e, "erm", ""))
        r.append(f"{gap[0]['mean'] - gap[1]['mean']:+.4f}"
                 if gap[0] and gap[1] else NM)
        rows.append(r)
    W(table(rows, ["representation"] + [f"`{p}`" for p in PROTOS]
            + ["iid − lot"]))
    W("")
    W("The `iid − lot` column is the part of a published random-split number "
      "that came from having seen the same lot in training. It is small. This "
      "was the surprise: the standard objection to random splits on WM-811K is "
      "that near-duplicate wafers from one lot land on both sides, and on this "
      "corpus that objection is worth little. The forward-only column is where "
      "the accuracy goes, and it is also the protocol with the largest label "
      "shift, so the drop is not purely covariate.")
    W("")

    # ---------------------------------------------------------------- result 2
    W("## 3. Result: the invariance toolbox does not beat ERM, "
      "and the reason is partly our own domain definition")
    W("")
    objs = sorted({k[2] for k in C if k[2] != "erm"})
    for p in ["lot", "size"]:
        rows = []
        for e in ["cnn_bn", "feat"]:
            base = stat(C, (p, e, "erm", ""))
            if not base:
                continue
            for o in objs:
                s = stat(C, (p, e, o, ""))
                if not s:
                    continue
                rows.append([ENC[e], f"`{o}`", fmt(s),
                             f"{s['mean'] - base['mean']:+.4f}"])
        if rows:
            W(f"**Protocol `{p}`** (deltas against the same encoder under ERM):")
            W("")
            W(table(rows, ["representation", "objective", "macro-F1", "vs ERM"]))
            W("")
            if any(r[1] == "`sinkhorn`" for r in rows):
                W("`sinkhorn` is not a result, it is a broken cell, and it is "
                  "shown rather than dropped so the table is not quietly "
                  "filtered. The entropic-OT penalty is minimized exactly by "
                  "collapsing the embedding to a point; at the default weight "
                  "the model converges smoothly to emitting the training class "
                  "prior, with validation macro-F1 identical at every epoch "
                  "from the first and training loss flat to four decimals for "
                  "the last four. `scripts/sinkhorn_lambda.sh` sweeps the "
                  "weight to establish whether any setting both trains and "
                  "penalizes; if none does, the row is removed rather than "
                  "left standing as evidence against optimal transport.")
                W("")

    dt = [(o, stat(C, ("lot", "cnn_bn", o, "dtime")),
           stat(C, ("lot", "cnn_bn", o, ""))) for o in ["erm"] + objs]
    dt = [(o, a_, b) for o, a_, b in dt if a_]
    W("### The domain definition was doing the work")
    W("")
    W("Every group-aware objective above received `lot % 32` as its domain "
      "label: 10,762 lots averaged into 32 buckets. Measured on this corpus, "
      "the mean pairwise total-variation distance between those buckets' class "
      "distributions is **0.0208**, against **0.1666** between real lots and "
      "**0.1822** between production-order deciles. An invariance penalty asked "
      "to equalize 32 distributions that are already equal to within 0.02 is "
      "satisfied by doing nothing, so ERM-equivalence on `lot` was close to "
      "guaranteed by construction rather than discovered.")
    W("")
    W("On `size` the same hash is far less degenerate — 344 geometries into 32 "
      "buckets, TV 0.2592 — which is why that protocol shows large, real and "
      "mostly negative effects. The `size` half of the negative result stands "
      "as measured; the `lot` half needed re-running.")
    W("")
    if dt:
        rows = [[f"`{o}`", fmt(b), fmt(a_),
                 f"{a_['mean'] - b['mean']:+.4f}" if b else NM]
                for o, a_, b in dt]
        W(table(rows, ["objective", "domain = `lot % 32`",
                       "domain = production decile", "difference"]))
        W("")
        W("`erm` never reads the domain label, so its two columns must agree "
          "exactly; it is included as the null control on the plumbing.")
    else:
        W(f"Re-run under a domain vocabulary that carries real shift: {NM}. "
          "`scripts/domain_def_sweep.sh` is queued. Until it lands, the claim "
          "\"borrowed domain-generalization objectives do not beat ERM on the "
          "`lot` protocol\" is **withdrawn** — not contradicted, withdrawn, "
          "because the experiment as run could not have shown otherwise.")
    W("")

    # ---------------------------------------------------------------- result 3
    W("## 4. Result: our own two contributions fail their own controls")
    W("")
    W("### 4.1 The RPCA lot-signature channel is matched by a channel of zeros")
    W("")
    W("Per-lot Robust PCA splits a lot's wafers into a low-rank part (what the "
      "lot shares — the tool signature) and a sparse part (this wafer's own "
      "defect), and the sparse part is handed to the CNN as a fourth input "
      "channel. Measured on `data/rpca.pt`: the low-rank part has **rank 0 for "
      "94.83%** of the 164,824 decomposed wafers, and the residual is "
      "bit-identical to the raw failed-die mask for **95.27%** of all 172,948 "
      "wafers. The channel is, for 19 wafers in 20, a second copy of one the "
      "one-hot input already carries.")
    W("")
    rows = []
    for p in ["lot", "lot_time", "size"]:
        base = stat(C, (p, "cnn_gn", "erm", ""))
        if not base:
            continue
        for tg, lab in [("", "RPCA residual (the claim)"),
                        ("failmask", "raw failed-die mask (control)"),
                        ("zerochan", "zeros (control)")]:
            s = stat(C, (p, "rpca_cnn", "erm", tg))
            if not s:
                continue
            rows.append([f"`{p}`", lab, fmt(s),
                         f"{s['mean'] - base['mean']:+.4f}"])
        rows.append([f"`{p}`", "*no fourth channel*", fmt(base), "—"])
    if rows:
        W(table(rows, ["protocol", "fourth channel", "macro-F1", "vs no channel"]))
        W("")
    W("On `lot` the three fourth-channel variants are separated from each other "
      "by less than the seed spread of any one of them. **A channel of zeros "
      "buys what the decomposition buys.** Whatever the fourth channel is worth "
      "there, it is worth as extra first-layer capacity, not as information "
      "about the tool. On `lot_time` the residual is ahead of both controls at "
      "every seed, which is the one place a genuine tool signature should help; "
      "the separation is below the controls' half-range at n=3, so we record it "
      "as a hypothesis and not a result.")
    W("")
    W("### 4.2 Lot-adversarial self-supervised pretraining is worse than "
      "random initialization")
    W("")
    ssl_rows = []
    for p in ["lot", "size", "lot_time"]:
        b = stat(C, (p, "cnn_gn", "erm", ""))
        s = stat(C, (p, "cnn_gn", "erm", "sslinit"))
        if not (b or s):
            continue
        ssl_rows.append([f"`{p}`", fmt(b), fmt(s),
                         f"{s['mean'] - b['mean']:+.4f}" if (b and s) else NM])
    if ssl_rows:
        W(table(ssl_rows, ["protocol", "from scratch", "SSL-initialized",
                           "difference"]))
        W("")
    sslj = Path(a.runs) / "ssl_pretrain.json"
    if sslj.exists():
        h = json.loads(sslj.read_text())
        ce = [x.get("nuisance_ce") for x in h["history"]]
        ch = h["history"][0].get("nuisance_ce_chance")
        W(f"Masked-die modelling on {h['n_unlabeled']:,} unlabelled wafers with "
          f"a gradient-reversed nuisance head, {h['minutes']:.1f} min. The "
          "adversary is supposed to drive the nuisance cross-entropy *up* "
          f"toward chance ({ch:.4f}); over {len(ce)} epochs it went "
          + ", ".join(f"{x:.4f}" for x in ce) +
          " — some traction, never reaching chance, not monotone. The "
          "embedding demonstrably still carries the nuisance, and the "
          "downstream result is consistent with that.")
        W("")
    W("The obvious alternative explanation is that the fine-tuning recipe is "
      "tuned for a random initialization: the pretrained weights are not at "
      "random-init scale (mean |w| of the deepest conv is 0.0852 in the "
      "checkpoint against 0.0147 for a fresh encoder, a factor of 5.8), and "
      "every cell above uses one LR on a OneCycle schedule. "
      "`scripts/ssl_lr_sweep.sh` runs both arms at four learning rates so the "
      "comparison is made LR by LR rather than best-of-treatment against "
      "one-shot-control.")
    W("")

    # ---------------------------------------------------------------- AL
    al = Path(a.runs) / "active_learning.json"
    W("## 5. Result: active learning loses to random lot selection")
    W("")
    if al.exists():
        d = json.loads(al.read_text())
        bud = d["budgets"]
        rows = [[s] + [f"{c[str(b)]['macro_f1_mean']:.4f}" for b in bud]
                for s, c in d["results"].items()]
        W(table(rows, ["strategy"] + [f"{b} lots" for b in bud]))
        W("")
        W(f"Budgets spent in whole lots out of {d['n_pool_lots']} available, "
          f"seeded with {d['seed_lots']} random lots, {d['seeds']} seeds, "
          "evaluated on the fixed lot-disjoint test split. Buying whole lots is "
          "what a fab actually does — a metrology slot is a lot, not a wafer — "
          "and it is exactly the setting where per-wafer uncertainty ranking "
          "has the least to offer.")
    else:
        W(NM)
    W("")

    # ---------------------------------------------------------------- seeds
    W("## 6. Seed spread is a result, not an appendix")
    W("")
    multi = {k: v for k, v in C.items() if len(v) > 1}
    if multi:
        rows = []
        for k in sorted(multi):
            s = stat(C, k)
            rows.append([f"`{k[0]}`", ENC.get(k[1], k[1]), f"`{k[2]}`",
                         k[3] or "—", s["n"], f"{s['mean']:.4f}",
                         f"±{s['hr']:.4f}"])
        W(table(rows, ["protocol", "representation", "objective", "variant",
                       "seeds", "mean macro-F1", "half-range"]))
        W("")
    W("A seed reshuffles the model initialization, which training domains become "
      "the inner validation split, and — for `lot` and `size` — which groups "
      "land in the test set. So this is the spread of the whole pipeline. The "
      "`size` protocol's spread is an order of magnitude larger than `lot`'s, "
      "because each seed holds out different geometries and geometries are "
      "heterogeneous. Any effect reported on `size` that is smaller than that "
      "spread is not an effect. `lot_time` is the tightest, and it is the only "
      "protocol whose test set does not move with the seed.")
    W("")

    # ---------------------------------------------------------------- mixed
    W("## 7. The multi-label question, and what we did not have")
    W("")
    mj = Path(a.runs) / "mixed_synth_dataset.json"
    W("WM-811K is single-label over nine classes. A multi-label F1 on it is not "
      "a defined quantity, so any figure of that shape in the literature is "
      "measured on something else — usually MixedWM38, 38 mixed-type classes. "
      "We could not obtain MixedWM38: the HuggingFace copy reachable from this "
      "machine is gated behind manual approval and the Zenodo record "
      "(10.5281/zenodo.20061545) returns HTTP 403 on its files.")
    W("")
    if mj.exists():
        d = json.loads(mj.read_text())
        W(f"We therefore constructed **MIXED-SYNTH**: {d['n_train']:,} training "
          f"and {d['n_test']:,} test wafers, of which {d['n_train_mixed']:,} and "
          f"{d['n_test_mixed']:,} are mixed-type wafers made by OR-ing the "
          "failed dies of two same-geometry WM-811K wafers. Label cardinality "
          f"in test is {d['test_label_cardinality_0_1_2']} for 0, 1 and 2 "
          "labels. Sources are lot-disjoint across the split by construction "
          "and the disjointness is asserted, not assumed.")
        W("")
        W("**MIXED-SYNTH is synthetic and is an upper bound.** Overlaid "
          "patterns do not interact: a real scratch crossing a real edge ring "
          "changes both signatures where they meet, and a pixel-wise OR has no "
          "such term. No number measured on MIXED-SYNTH is a statement about "
          "WM-811K or about MixedWM38.")
        W("")
    mixed = sorted(Path(a.runs).glob("mixedsynth__*.json"))
    if mixed:
        rows = []
        for p in mixed:
            r = json.loads(p.read_text())
            rows.append([r["protocol"], f"`{r['loss']}`", r["seed"],
                         f"{r['test_at_0.5']['macro_f1']:.4f}",
                         f"{r['test_at_val_tuned_thresholds']['macro_f1']:.4f}",
                         f"{r['test_at_val_tuned_thresholds']['micro_f1']:.4f}",
                         f"{r['test_at_val_tuned_thresholds']['subset_accuracy']:.4f}"])
        W(table(rows, ["source split", "loss", "seed", "macro-F1 @0.5",
                       "macro-F1 @tuned", "micro-F1 @tuned", "subset acc."]))
        W("")
        W("Thresholds are tuned per class on a lot-disjoint validation split "
          "carved from training, never on test. Both numbers are given because "
          "threshold tuning is worth several points on a long-tailed label set "
          "and the two are different metrics.")
    else:
        W(f"MIXED-SYNTH training results: {NM}. `scripts/mixed_sweep.sh` queued.")
    W("")

    # ---------------------------------------------------------------- threats
    W("## 8. Threats to validity")
    W("")
    W("1. **Time is a proxy.** WM-811K carries no timestamps. `lot_time` orders "
      "lots by the integer in the lot name, on the assumption that a fab issues "
      "lot numbers in production order. If that assumption fails the "
      "forward-only protocol is measuring something else, and it is our largest "
      "single result.")
    W("2. **The test split is label-aware.** `_stratified_group_split` skips a "
      "candidate held-out group when moving it would leave a class with no "
      "training examples. No label reaches the model, but which domains land in "
      "test is not independent of the labels; the guard binds almost only on "
      "`Near-full` (149 wafers). The size of the resulting bias is " + NM + ".")
    W("3. **One architecture family.** Every CNN cell is the same three-block "
      "encoder at width 32 and 12 epochs. Whether the protocol ordering "
      "survives at a modern backbone and a longer schedule is " + NM + ".")
    W("4. **Three seeds.** Half-ranges over three seeds are descriptive, not "
      "inferential. We report the range we saw and do not attach a p-value to "
      "it.")
    W("")

    W("## 9. What is deliberately not claimed")
    W("")
    W("We do not claim a state-of-the-art WM-811K number. The best cell here "
      f"under a lot-disjoint split is {fmt(stat(C, ('lot', 'cnn_gn', 'erm', '')))} "
      "macro-F1 for a small CNN; published figures near 0.95 are typically "
      "9-class iid splits on the labelled subset with heavy augmentation, which "
      "is our `iid` column and a different quantity. The contribution is the "
      "ordering of the protocols and the failure of the methods, not the "
      "leaderboard position.")
    W("")

    Path(a.out).write_text("\n".join(L) + "\n")
    print(f"wrote {a.out} from {len(C)} cells")


if __name__ == "__main__":
    main()
