"""Regenerate RESULTS.md from runs/*.json. Nothing here is hand-typed."""
from __future__ import annotations

import sys
from pathlib import Path as _P
sys.path.insert(0, str(_P(__file__).resolve().parents[1]))

import argparse
import json
from pathlib import Path

from wts.data import CLASSES


def cell(x):
    return str(x).replace("|", "\\|")


def table(rows, header):
    out = ["| " + " | ".join(cell(h) for h in header) + " |",
           "|" + "|".join(["---"] * len(header)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(cell(c) for c in r) + " |")
    return "\n".join(out)


def f(x, n=4):
    return "-" if x is None else f"{x:.{n}f}"


def load(run_dir):
    out = {}
    for p in sorted(Path(run_dir).glob("*.json")):
        r = json.loads(p.read_text())
        out[(r["protocol"], r["encoder"], r["objective"], r.get("tag", ""))] = r
    return out


ENC_LABEL = {
    "feat": "size-invariant descriptors + MLP",
    "cnn_bn": "CNN on resized 64x64 (BatchNorm)",
    "cnn_gn": "CNN on resized 64x64 (GroupNorm)",
    "spectral": "spectral operator, native resolution",
    "graph": "die-graph GNN (wafer-only subgraph)",
    "rpca_cnn": "CNN + RPCA lot-signature channel",
}
TAG_LABEL = {
    "": "-",
    "rpcafeat": "+ RPCA lot signature as features",
    "fda": "+ Fourier amplitude swap augmentation",
    "sslinit": "+ lot-adversarial SSL initialization",
}
OBJ_NOTE = {
    "erm": "-",
    "hsic": "kernel independence testing",
    "sinkhorn": "optimal transport",
    "anchor": "econometrics / anchor regression",
    "logit_adjust": "long-tail recognition",
    "group_dro": "robust optimization",
    "dann": "domain adaptation",
    "irm": "causal inference",
    "coral": "domain adaptation",
    "mixup_domain": "vicinal risk / LISA",
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", default="runs")
    ap.add_argument("--out", default="RESULTS.md")
    args = ap.parse_args()
    R = load(args.runs)
    if not R:
        print("no runs yet")
        return

    L = ["# Results", "",
         "Regenerated by `scripts/report.py` from the JSON each cell writes; no "
         "number here is typed by hand. Model selection for every cell uses a "
         "**domain-disjoint validation split carved out of the training "
         "domains** -- never the test domains.", ""]

    any_run = next(iter(R.values()))
    protos = sorted({k[0] for k in R})
    L += ["## The three protocols", "",
          table([[p,
                  f(next(r["label_shift_tv"] for k, r in R.items() if k[0] == p), 4),
                  next(r["n_train"] for k, r in R.items() if k[0] == p),
                  next(r["n_val"] for k, r in R.items() if k[0] == p),
                  next(r["n_test"] for k, r in R.items() if k[0] == p)]
                 for p in protos],
                ["protocol", "label shift (TV)", "train", "val (OOD)", "test"]),
          "",
          "`iid` splits wafers at random, `lot` holds out whole lots, `size` "
          "holds out whole wafer geometries. The label marginal cannot be held "
          "fixed while holding out groups, so the shift it induces is measured "
          "rather than ignored.", ""]

    # ---- stage A
    encs = [e for e in ENC_LABEL if any(k[1] == e for k in R)]
    rows = []
    for e in encs:
        for p in protos:
            r = R.get((p, e, "erm", ""))
            if not r:
                continue
            t = r["test"]
            rows.append([ENC_LABEL[e], p, f(t["macro_f1"]), f(t["defect_macro_f1"]),
                         f(t.get("p10_domain_macro_f1")),
                         f(t.get("worst_domain_macro_f1")),
                         f(t["defect_auroc"]), f(t["ece"]),
                         f(t.get("conformal_coverage"), 3),
                         f"{r['params_m']:.2f}M", f"{r['minutes']:.1f} min"])
    if rows:
        L += ["## Representations under plain ERM", "",
              table(rows, ["representation", "protocol", "macro-F1", "defect macro-F1",
                           "p10 domain F1", "worst domain F1", "defect AUROC",
                           "ECE", "conformal cov.", "params", "wall"]), ""]

    # ---- the headline gap
    gaps = []
    for e in encs:
        a, b, c = (R.get(("iid", e, "erm", "")), R.get(("lot", e, "erm", "")),
                   R.get(("size", e, "erm", "")))
        if not (a and b):
            continue
        gaps.append([ENC_LABEL[e], f(a["test"]["macro_f1"]), f(b["test"]["macro_f1"]),
                     f(a["test"]["macro_f1"] - b["test"]["macro_f1"]),
                     f(c["test"]["macro_f1"]) if c else "-",
                     f(a["test"]["macro_f1"] - c["test"]["macro_f1"]) if c else "-"])
    if gaps:
        L += ["### How much of the reported accuracy was leakage", "",
              "The gap between a random wafer split and a lot-disjoint split is "
              "the part of a published number that came from having seen the "
              "same lot in training.", "",
              table(gaps, ["representation", "iid macro-F1", "lot macro-F1",
                           "iid - lot", "size macro-F1", "iid - size"]), ""]

    # ---- stage B
    objs = [o for o in OBJ_NOTE if o != "erm" and any(k[2] == o for k in R)]
    for p in [x for x in protos if x != "iid"]:
        rows = []
        for e in encs:
            base = R.get((p, e, "erm", ""))
            if not base:
                continue
            for o in ["erm"] + objs:
                r = R.get((p, e, o, ""))
                if not r:
                    continue
                t, bt = r["test"], base["test"]
                rows.append([
                    ENC_LABEL[e], o, OBJ_NOTE[o], f(t["macro_f1"]),
                    ("-" if o == "erm"
                     else f"{t['macro_f1'] - bt['macro_f1']:+.4f}"),
                    f(t.get("p10_domain_macro_f1")),
                    ("-" if o == "erm" else
                     f"{(t.get('p10_domain_macro_f1') or 0) - (bt.get('p10_domain_macro_f1') or 0):+.4f}"),
                    f(t["per_class_f1"].get("Scratch")),
                    f(t["per_class_f1"].get("Near-full")),
                ])
        if rows:
            L += [f"## Borrowed objectives vs ERM -- protocol `{p}`", "",
                  table(rows, ["representation", "objective", "borrowed from",
                               "macro-F1", "vs ERM", "p10 domain F1",
                               "vs ERM", "Scratch F1", "Near-full F1"]), ""]

    # ---- TTA
    rows = []
    for (p, e, o, tg), r in sorted(R.items()):
        for name in ("adabn", "tent", "ema"):
            key = f"test_{name}"
            if key in r:
                rows.append([p, ENC_LABEL[e], f"{o}{'/' + tg if tg else ''}", name,
                             f(r["test"]["macro_f1"]), f(r[key]["macro_f1"]),
                             f"{r[key]['macro_f1'] - r['test']['macro_f1']:+.4f}"])
    if rows:
        L += ["## Test-time adaptation and weight averaging", "",
              "`adabn` and `tent` use only the *unlabelled* test wafers -- what a "
              "fab has when a new tool comes online. `ema` is the averaged "
              "weights, a free check on whether flatness helped.", "",
              table(rows, ["protocol", "representation", "objective", "method",
                           "base macro-F1", "after", "delta"]), ""]

    # ---- tagged variants against their untagged twin
    rows = []
    for (p, e, o, tg), r in sorted(R.items()):
        if not tg:
            continue
        base = R.get((p, e, o, ""))
        t = r["test"]
        rows.append([p, ENC_LABEL[e], TAG_LABEL.get(tg, tg), f(t["macro_f1"]),
                     ("-" if not base else
                      f"{t['macro_f1'] - base['test']['macro_f1']:+.4f}"),
                     f(t.get("p10_domain_macro_f1")),
                     ("-" if not base else
                      f"{(t.get('p10_domain_macro_f1') or 0) - (base['test'].get('p10_domain_macro_f1') or 0):+.4f}")])
    if rows:
        L += ["## Variants, against the same cell without them", "",
              table(rows, ["protocol", "representation", "variant", "macro-F1",
                           "vs plain", "p10 domain F1", "vs plain"]), ""]

    # ---- active learning
    al_path = Path("runs/active_learning.json")
    if al_path.exists():
        al = json.loads(al_path.read_text())
        budgets = al["budgets"]
        rows = []
        for strat, curve in al["results"].items():
            rows.append([strat] + [f"{curve[str(b)]['macro_f1_mean']:.4f}"
                                   for b in budgets])
        L += ["## Which lots to pay to measure", "",
              f"Budgets are spent in whole lots out of {al['n_pool_lots']} "
              f"available, seeded with {al['seed_lots']} random lots, "
              f"{al['seeds']} seeds. Test set is the fixed lot-disjoint split.",
              "",
              table(rows, ["strategy"] + [f"{b} lots" for b in budgets]), ""]

    # ---- SSL pretraining
    ssl_path = Path("runs/ssl_pretrain.json")
    if ssl_path.exists():
        ssl = json.loads(ssl_path.read_text())
        h = ssl["history"]
        L += ["## Lot-adversarial self-supervised pretraining", "",
              f"Masked-die modelling on {ssl['n_unlabeled']:,} unlabelled "
              f"wafers with a gradient-reversed lot head, "
              f"{ssl['minutes']:.1f} min.", "",
              table([[r["epoch"], f(r["recon_ce"]), f(r["lot_ce"]),
                      f(r["lot_ce_chance"])] for r in h],
                    ["epoch", "masked-die CE", "lot CE (adversarial)",
                     "lot CE at chance"]),
              "",
              "The lot CE rising toward chance is the signal that the embedding "
              "is losing its ability to name its own lot.", ""]

    # ---- per-class for the best lot-protocol cell
    lot_cells = {k: v for k, v in R.items() if k[0] == "lot"}
    if lot_cells:
        best_k = max(lot_cells, key=lambda k: lot_cells[k]["test"]["macro_f1"])
        t = lot_cells[best_k]["test"]
        L += [f"## Per-class F1, best `lot` cell ({ENC_LABEL[best_k[1]]}, "
              f"{best_k[2]})", "",
              table([[c, f(t["per_class_f1"][c])] for c in CLASSES],
                    ["class", "F1"]), "",
              "The long tail is where the shift bites: `Near-full` has 149 "
              "examples in the whole corpus and `Scratch` is a one-die-wide "
              "line, which global descriptors average away.", ""]

    Path(args.out).write_text("\n".join(L) + "\n")
    print(f"wrote {args.out} from {len(R)} cells")


if __name__ == "__main__":
    main()
