"""Regenerate RESULTS.md from runs/*.json. Nothing here is hand-typed."""
from __future__ import annotations

import sys
from pathlib import Path as _P
sys.path.insert(0, str(_P(__file__).resolve().parents[1]))

import argparse
import json
from pathlib import Path

import numpy as np

from wts.data import CLASSES


def cell(x):
    return str(x).replace("|", "\\|")


def table(rows, header):
    out = ["| " + " | ".join(cell(h) for h in header) + " |",
           "|" + "|".join(["---"] * len(header)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(cell(c) for c in r) + " |")
    return "\n".join(out)


def f(x, n=4):
    return "-" if x is None else f"{x:.{n}f}"


def load(run_dir):
    """Benchmark cells only -- `runs/` also holds the active-learning curve, the
    RPCA lambda sweep and the pretraining history, which have their own shapes.

    Keyed by seed as well as by cell. An earlier version left the seed out of
    the key, so a second seed of a cell overwrote the first and whichever file
    sorted last won silently. Every table below either takes the reference seed
    explicitly or aggregates over the seeds it found.
    """
    out = {}
    for p in sorted(Path(run_dir).glob("*.json")):
        r = json.loads(p.read_text())
        # a cell is identified by having all three axes, not by "protocol"
        # alone: runs/ also holds the MIXED-SYNTH dataset summary and the
        # MIXED-SYNTH training results, which carry a protocol and nothing else
        # a benchmark table can use
        if not isinstance(r, dict) or not {"protocol", "encoder",
                                           "objective"} <= set(r):
            continue
        out[(r["protocol"], r["encoder"], r["objective"], r.get("tag", ""),
             r.get("seed", 0))] = r
    return out


REF_SEED = 0


def by_cell(runs):
    """(protocol, encoder, objective, tag) -> {seed: record}."""
    out = {}
    for (p, e, o, tg, sd), r in runs.items():
        out.setdefault((p, e, o, tg), {})[sd] = r
    return out


def spread(vals):
    """mean and half-range. Half-range, not a standard error: with three seeds
    an SE is a fiction, and the half-range is what you actually saw."""
    return sum(vals) / len(vals), (max(vals) - min(vals)) / 2


ENC_LABEL = {
    "feat": "size-invariant descriptors + MLP",
    "cnn_bn": "CNN on resized 64x64 (BatchNorm)",
    "cnn_gn": "CNN on resized 64x64 (GroupNorm)",
    "spectral": "spectral operator, native resolution",
    "graph": "die-graph GNN (wafer-only subgraph)",
    "rpca_cnn": "CNN + RPCA lot-signature channel",
}
TAG_LABEL = {
    "": "-",
    "rpcafeat": "+ RPCA lot signature as features",
    "fda": "+ Fourier amplitude swap augmentation",
    "sslinit": "+ lot-adversarial SSL initialization",
    "failmask": "4th channel = raw failed-die mask (RPCA control)",
    "zerochan": "4th channel = zeros (RPCA control)",
}
OBJ_NOTE = {
    "erm": "-",
    "hsic": "kernel independence testing",
    "sinkhorn": "optimal transport",
    "anchor": "econometrics / anchor regression",
    "logit_adjust": "long-tail recognition",
    "group_dro": "robust optimization",
    "dann": "domain adaptation",
    "irm": "causal inference",
    "coral": "domain adaptation",
    "mixup_domain": "vicinal risk / LISA",
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", default="runs")
    ap.add_argument("--out", default="RESULTS.md")
    args = ap.parse_args()
    runs = load(args.runs)
    if not runs:
        print("no runs yet")
        return
    SEEDS = by_cell(runs)
    # every pre-existing table is a single-seed table and is kept that way, so
    # the numbers stay comparable to what was reported before seeds were added
    R = {k: v[min(v, key=lambda sd: abs(sd - REF_SEED))] for k, v in SEEDS.items()}

    L = ["# Results", "",
         "Regenerated by `scripts/report.py` from the JSON each cell writes; no "
         "number here is typed by hand. Model selection for every cell uses a "
         "**domain-disjoint validation split carved out of the training "
         "domains** -- never the test domains.", "",
         f"Unless a table says otherwise every cell below is **seed "
         f"{REF_SEED} only**. Seed spread is not decoration on this corpus: see "
         "*Seed spread* below, where it is larger than most of the effects "
         "reported in the objective tables.", ""]

    any_run = next(iter(R.values()))
    protos = sorted({k[0] for k in R})
    L += ["## The three protocols", "",
          table([[p,
                  f(next(r["label_shift_tv"] for k, r in R.items() if k[0] == p), 4),
                  next(r["n_train"] for k, r in R.items() if k[0] == p),
                  next(r["n_val"] for k, r in R.items() if k[0] == p),
                  next(r["n_test"] for k, r in R.items() if k[0] == p)]
                 for p in protos],
                ["protocol", "label shift (TV)", "train", "val (OOD)", "test"]),
          "",
          "`iid` splits wafers at random, `lot` holds out whole lots, `size` "
          "holds out whole wafer geometries. The label marginal cannot be held "
          "fixed while holding out groups, so the shift it induces is measured "
          "rather than ignored.", ""]

    # ---- stage A
    encs = [e for e in ENC_LABEL if any(k[1] == e for k in R)]

    def seedstat(key):
        """mean, half-range and count of test macro-F1 over the seeds present."""
        v = SEEDS.get(key)
        if not v:
            return None
        xs = sorted(r["test"]["macro_f1"] for r in v.values())
        return sum(xs) / len(xs), (max(xs) - min(xs)) / 2, len(xs)

    rows = []
    for e in encs:
        for p in protos:
            r = R.get((p, e, "erm", ""))
            if not r:
                continue
            t = r["test"]
            st = seedstat((p, e, "erm", ""))
            rows.append([ENC_LABEL[e], p, f(t["macro_f1"]),
                         (f"{st[0]:.4f} ±{st[1]:.4f} (n={st[2]})"
                          if st and st[2] > 1 else f"n=1"),
                         f(t["defect_macro_f1"]),
                         f(t.get("p10_domain_macro_f1")),
                         f(t.get("worst_domain_macro_f1")),
                         f(t["defect_auroc"]), f(t["ece"]),
                         f(t.get("conformal_coverage"), 3),
                         f"{r['params_m']:.2f}M", f"{r['minutes']:.1f} min"])
    if rows:
        L += ["## Representations under plain ERM", "",
              table(rows, ["representation", "protocol", "macro-F1 (seed 0)",
                           "over seeds", "defect macro-F1",
                           "p10 domain F1", "worst domain F1", "defect AUROC",
                           "ECE", "conformal cov.", "params", "wall"]), "",
              "The `macro-F1 (seed 0)` column is the original single-seed "
              "measurement, kept so nothing silently changes value; `over "
              "seeds` is the mean and half-range wherever more than one seed "
              "exists. **Where it reads `n=1` the number has no error bar and "
              "the ordering around it is not established.** Measured "
              "half-ranges are 0.0044-0.0096 on `lot` and 0.031-0.036 on "
              "`size`, which is the size of the gaps between the middle "
              "representations, so those gaps are not resolvable until the "
              "seeds exist. `scripts/backfill_metrics.sh` runs all 22 "
              "(protocol, representation) pairs at three seeds.", "",
              "Three caveats on the last four columns, all of which came out of "
              "reading this table adversarially rather than from a new run:", "",
              "* `p10 domain F1` and `worst domain F1` are quantized on the "
              "`lot` protocol -- see the note under the objective tables. They "
              "are informative on `size`, whose domains are large.",
              "* `ECE` is top-1 expected calibration error, weighted by sample "
              "count. 85% of this corpus is `none` and is predicted at high "
              "confidence and high accuracy, so the statistic is dominated by "
              "the easy majority and stays below 0.01 even where macro-F1 "
              "collapses. It is not a metric a model cannot game; treat it as a "
              "sanity check on the majority class only.",
              "* `conformal cov.` is built from *class-conditional* thresholds "
              "but reported as a single average over the test set, which turns "
              "it back into a marginal number that `none` dominates. "
              "`summarize` now also emits per-class coverage, the worst class, "
              "and the empty-prediction-set rate; cells measured before that "
              "change do not carry them.", ""]

    # ---- is the representation ordering resolvable at the measured noise?
    det_p = Path("runs/determinism.json")
    floor = (json.loads(det_p.read_text())["run_to_run_abs_diff"]
             if det_p.exists() else None)
    res_rows = []
    for p in protos:
        vals = {}
        for e in encs:
            v = SEEDS.get((p, e, "erm", ""))
            if v:
                vals[e] = sorted(r["test"]["macro_f1"] for r in v.values())
        order = sorted(vals, key=lambda e: -sum(vals[e]) / len(vals[e]))
        for a_, b_ in zip(order, order[1:]):
            xa, xb = vals[a_], vals[b_]
            gap = sum(xa) / len(xa) - sum(xb) / len(xb)
            if len(xa) == 1 or len(xb) == 1:
                verdict = "no error bar (n=1)"
            elif min(xa) > max(xb):
                m = min(xa) - max(xb)
                verdict = (f"ranges disjoint by {m:.4f}"
                           + ("" if floor is None or m > 3 * floor
                              else " -- below the run-to-run floor"))
            else:
                verdict = "ranges overlap"
            res_rows.append([f"`{p}`", ENC_LABEL.get(a_, a_),
                             ENC_LABEL.get(b_, b_), f"{gap:+.4f}",
                             f"{len(xa)}/{len(xb)}", verdict])
    if res_rows:
        L += ["### Is that ordering resolvable?", "",
              "Each adjacent pair in the ranking above, per protocol, with the "
              "verdict from whether the observed seed ranges overlap. This is "
              "deliberately non-parametric: three seeds do not support a "
              "p-value, but whether one cell's worst seed beat the other's best "
              "is a fact about what was seen."
              + (f" The run-to-run floor -- two identical invocations of one "
                 f"cell -- is {floor:.2e}, so a margin near that is not a "
                 f"separation." if floor is not None else ""), "",
              table(res_rows, ["protocol", "higher", "lower", "gap",
                               "seeds", "verdict"]), ""]

    # ---- "GroupNorm beats BatchNorm everywhere", checked as its own claim
    nrm = []
    for p in protos:
        g = SEEDS.get((p, "cnn_gn", "erm", ""))
        b = SEEDS.get((p, "cnn_bn", "erm", ""))
        if not (g and b):
            continue
        xg = sorted(r["test"]["macro_f1"] for r in g.values())
        xb = sorted(r["test"]["macro_f1"] for r in b.values())
        gap = sum(xg) / len(xg) - sum(xb) / len(xb)
        if len(xg) == 1 or len(xb) == 1:
            v = "no error bar (n=1)"
        elif min(xg) > max(xb):
            m = min(xg) - max(xb)
            v = (f"every GN seed above every BN seed, margin {m:.4f}"
                 + ("" if floor is None or m > 3 * floor
                    else f" -- below the {floor:.2e} run-to-run floor"))
        elif min(xb) > max(xg):
            v = "every BN seed above every GN seed"
        else:
            v = "ranges overlap"
        nrm.append([f"`{p}`", f"{sum(xg)/len(xg):.4f}", f"{sum(xb)/len(xb):.4f}",
                    f"{gap:+.4f}", f"{len(xg)}/{len(xb)}", v])
    if nrm:
        L += ["### GroupNorm against BatchNorm", "",
              "A separate claim from the ranking, because BatchNorm mixes "
              "statistics across whatever is in the batch and a batch here "
              "spans lots -- so the normalization choice is a domain-leak "
              "question, not a tuning one. `spectral` sits between the two in "
              "the overall ranking, so this pair does not appear as adjacent "
              "above and is checked directly.", "",
              table(nrm, ["protocol", "GroupNorm", "BatchNorm", "GN - BN",
                          "seeds", "verdict"]), ""]

    # ---- the headline gap
    gaps = []
    for e in encs:
        a, b, c = (R.get(("iid", e, "erm", "")), R.get(("lot", e, "erm", "")),
                   R.get(("size", e, "erm", "")))
        if not (a and b):
            continue
        gaps.append([ENC_LABEL[e], f(a["test"]["macro_f1"]), f(b["test"]["macro_f1"]),
                     f(a["test"]["macro_f1"] - b["test"]["macro_f1"]),
                     f(c["test"]["macro_f1"]) if c else "-",
                     f(a["test"]["macro_f1"] - c["test"]["macro_f1"]) if c else "-"])
    if gaps:
        L += ["### How much of the reported accuracy was leakage", "",
              "The gap between a random wafer split and a lot-disjoint split is "
              "the part of a published number that came from having seen the "
              "same lot in training.", "",
              table(gaps, ["representation", "iid macro-F1", "lot macro-F1",
                           "iid - lot", "size macro-F1", "iid - size"]), ""]

    # ---- stage B
    objs = [o for o in OBJ_NOTE if o != "erm" and any(k[2] == o for k in R)]
    for p in [x for x in protos if x != "iid"]:
        rows = []
        for e in encs:
            base = R.get((p, e, "erm", ""))
            if not base:
                continue
            for o in ["erm"] + objs:
                r = R.get((p, e, o, ""))
                if not r:
                    continue
                t, bt = r["test"], base["test"]
                rows.append([
                    ENC_LABEL[e], o, OBJ_NOTE[o], f(t["macro_f1"]),
                    ("-" if o == "erm"
                     else f"{t['macro_f1'] - bt['macro_f1']:+.4f}"),
                    f(t.get("p10_domain_macro_f1")),
                    ("-" if o == "erm" else
                     f"{(t.get('p10_domain_macro_f1') or 0) - (bt.get('p10_domain_macro_f1') or 0):+.4f}"),
                    f(t["per_class_f1"].get("Scratch")),
                    f(t["per_class_f1"].get("Near-full")),
                ])
        if rows:
            L += [f"## Borrowed objectives vs ERM -- protocol `{p}`", "",
                  table(rows, ["representation", "objective", "borrowed from",
                               "macro-F1", "vs ERM", "p10 domain F1",
                               "vs ERM", "Scratch F1", "Near-full F1"]), "",
                  "**Do not rank models by the `p10 domain F1` column.** A lot "
                  "holds at most 25 wafers, so a per-lot macro-F1 takes very "
                  "few distinct values -- a 25-wafer lot whose one defect is "
                  "missed scores exactly (48/49 + 0)/2 = 0.4898 whichever model "
                  "missed it. Across the cells in `runs/`, 25 separate `lot` "
                  "cells report that identical 0.4898 and 11 more report "
                  "exactly 0.5000, so the column is a discretization artefact "
                  "of lot size rather than a measure of domain robustness. "
                  "`wts.metrics.summarize` now also emits "
                  "`mean_domain_macro_f1` and `frac_domains_below_half`, which "
                  "average over ~1,700 lots and therefore do separate models; "
                  "cells measured before that change do not carry them.", ""]

    # ---- TTA
    rows = []
    for (p, e, o, tg), r in sorted(R.items()):
        for name in ("adabn", "tent", "ema"):
            key = f"test_{name}"
            if key in r:
                rows.append([p, ENC_LABEL[e], f"{o}{'/' + tg if tg else ''}", name,
                             f(r["test"]["macro_f1"]), f(r[key]["macro_f1"]),
                             f"{r[key]['macro_f1'] - r['test']['macro_f1']:+.4f}"])
    if rows:
        L += ["## Test-time adaptation and weight averaging", "",
              "`adabn` and `tent` use only the *unlabelled* test wafers -- what a "
              "fab has when a new tool comes online. `ema` is the averaged "
              "weights, a free check on whether flatness helped.", "",
              table(rows, ["protocol", "representation", "objective", "method",
                           "base macro-F1", "after", "delta"]), ""]

    # ---- tagged variants against their untagged twin
    rows = []
    for (p, e, o, tg), r in sorted(R.items()):
        if not tg:
            continue
        base = R.get((p, e, o, ""))
        t = r["test"]
        rows.append([p, ENC_LABEL[e], TAG_LABEL.get(tg, tg), f(t["macro_f1"]),
                     ("-" if not base else
                      f"{t['macro_f1'] - base['test']['macro_f1']:+.4f}"),
                     f(t.get("p10_domain_macro_f1")),
                     ("-" if not base else
                      f"{(t.get('p10_domain_macro_f1') or 0) - (base['test'].get('p10_domain_macro_f1') or 0):+.4f}")])
    if rows:
        L += ["## Variants, against the same cell without them", "",
              table(rows, ["protocol", "representation", "variant", "macro-F1",
                           "vs plain", "p10 domain F1", "vs plain"]), ""]

    # ---- seed spread, wherever more than one seed exists
    multi = {k: v for k, v in SEEDS.items() if len(v) > 1}
    if multi:
        rows = []
        for (p, e, o, tg) in sorted(multi):
            v = multi[(p, e, o, tg)]
            f1 = [r["test"]["macro_f1"] for r in sorted(v.values(),
                                                        key=lambda r: r["seed"])]
            m, hr = spread(f1)
            rows.append([p, ENC_LABEL.get(e, e), o, TAG_LABEL.get(tg, tg) if tg else "-",
                         len(v), f(m), f"+/-{hr:.4f}",
                         ", ".join(f"{x:.4f}" for x in f1)])
        L += ["## Seed spread", "",
              "Each seed reshuffles the model init *and* which training domains "
              "become the inner validation split, so this is the spread of the "
              "whole pipeline, not of the optimizer alone. It is the yardstick "
              "any claimed improvement has to clear.", "",
              table(rows, ["protocol", "representation", "objective", "variant",
                           "seeds", "mean macro-F1", "half-range", "per seed"]),
              ""]

    # ---- what the rpca_cnn fourth channel is actually worth
    abl = []
    for p in protos:
        got = {tg: SEEDS.get((p, "rpca_cnn", "erm", tg))
               for tg in ("", "failmask", "zerochan")}
        base = SEEDS.get((p, "cnn_gn", "erm", ""))
        if not got[""] or not base:
            continue
        def agg(v):
            if not v:
                return "-", "-", 0
            f1 = [r["test"]["macro_f1"] for r in v.values()]
            m, hr = spread(f1)
            return f(m), f"+/-{hr:.4f}", len(v)
        bm, bhr, bn = agg(base)
        for tg, label in ((None, "cnn_gn, 3 channels (no fourth channel)"),
                          ("", "4th = RPCA residual (the claim)"),
                          ("failmask", "4th = raw failed-die mask (control)"),
                          ("zerochan", "4th = zeros (control)")):
            v = base if tg is None else got[tg]
            if not v:
                continue
            m, hr, n = agg(v)
            delta = ("-" if tg is None else
                     f"{sum(r['test']['macro_f1'] for r in v.values()) / len(v) - sum(r['test']['macro_f1'] for r in base.values()) / len(base):+.4f}")
            abl.append([p, label, n, m, hr, delta])
    if abl:
        L += ["## What the `rpca_cnn` fourth channel is worth", "",
              "`rpca_cnn` was the best `lot` cell and the stated reason was that "
              "its fourth channel carries the wafer's defect with the lot's tool "
              "signature removed. But the per-lot RPCA returns a **rank-0** "
              "low-rank part for 94.8% of decomposed lots, and the residual it "
              "hands the encoder is bit-identical to the raw failed-die mask for "
              "95.3% of all 172,948 wafers (`scripts/ablate_sigchannel.sh`). "
              "The two controls replace that channel with the raw mask and with "
              "zeros. Read this table against *Seed spread* above.", "",
              table(abl, ["protocol", "fourth channel", "seeds",
                          "mean macro-F1", "half-range", "vs cnn_gn"]), ""]

    # ---- what each protocol actually holds out, and the reproducibility floor
    tp = Path("runs/time_proxy.json")
    if tp.exists():
        d = json.loads(tp.read_text())
        sg = d.get("split_geometry", {})
        if sg:
            L += ["## What each protocol actually holds out", "",
                  "A property of the splits, computed without any model. It "
                  "matters because `lot_time` is read as a *temporal* protocol "
                  "and its test side is also a narrow slice of geometry space.",
                  "",
                  table([[f"`{k}`", v["n_geometries_train"],
                          v["n_geometries_test"], v["n_geometries_test_unseen"],
                          f"{v['n_test_wafers_unseen_geometry']:,}",
                          f"{v['frac_test_wafers_unseen_geometry']:.2%}"]
                         for k, v in sg.items()],
                        ["protocol", "geometries in train", "in test",
                         "in test, unseen in train",
                         "test wafers of unseen geometry", "as a fraction"]),
                  ""]
            lt = sg.get("lot_time", {})
            L += [f"The forward-only protocol trains on "
                  f"{lt.get('n_geometries_train','?')} geometries and tests on "
                  f"**{lt.get('n_geometries_test','?')}**, with "
                  f"{lt.get('frac_test_wafers_unseen_geometry',0):.2%} of its "
                  "test wafers of a geometry never trained on. Part of its "
                  "accuracy drop is geometry shift rather than time. The "
                  "per-cell `test_seen_geometry` / `test_unseen_geometry` "
                  "fields split it; cells measured before those were added do "
                  "not carry them.", ""]
        tv = d.get("variables", {})
        if tv:
            L += ["### Is the lot numbering production order?", "",
                  "It cannot be proved; it can be refuted as arbitrary. "
                  "Deciles of lot number, distributional distance against "
                  f"decile gap, versus {d['null_draws']} reassignments of "
                  "numbers to lots that preserve every lot's contents:", "",
                  table([[f"`{k}`", f"{v['spearman_gap_vs_tv']:+.4f}",
                          f"{v['null_p95']:.4f}",
                          f"{v['p_value_one_sided']:.3f}"]
                         for k, v in tv.items()],
                        ["variable", "Spearman(gap, TV)", "null p95",
                         "p (one-sided)"]),
                  "",
                  "Geometry and failed-die rate drift with lot number; the "
                  "defect-class mix does not. The numbering is not arbitrary, "
                  "but this cannot separate production order from product "
                  "blocking -- a product line numbered in a contiguous block "
                  "gives the same signature.", ""]

    det = Path("runs/determinism.json")
    if det.exists():
        dd = json.loads(det.read_text())
        L += ["## Run-to-run reproducibility floor", "",
              f"`{dd['cell']}`, run twice under identical arguments: "
              f"{dd['run_a_macro_f1']:.6f} and {dd['run_b_macro_f1']:.6f}, "
              f"differing by **{dd['run_to_run_abs_diff']:.2e}**"
              + ("(bit-reproducible)." if dd["bit_reproducible"] else
                 " -- the pipeline is not bit-reproducible on this GPU.") + " "
              + dd["note"], ""]

    # ---- seen / unseen geometry, wherever a cell carries it
    def matched_macro(sgy, ugy):
        """macro-F1 of each half over the classes *both* halves contain.

        The raw macro-F1 of the two halves averages over different class sets,
        so a difference between them can be entirely a difference in which
        classes happened to be present. Restricting both to the shared classes
        makes the comparison mean what a reader will assume it means.
        """
        if not (sgy and ugy):
            return None, None, 0
        shared = sorted(set(sgy["classes_present"]) & set(ugy["classes_present"]))
        if not shared:
            return None, None, 0
        m = lambda r: sum(r["per_class_f1"][c] for c in shared) / len(shared)
        return m(sgy), m(ugy), len(shared)

    rows = []
    for (p, e, o, tg), r in sorted(R.items()):
        if "n_test_seen_geometry" not in r:
            continue
        sgy, ugy = r.get("test_seen_geometry"), r.get("test_unseen_geometry")
        ms, mu, nsh = matched_macro(sgy, ugy)
        rows.append([p, ENC_LABEL.get(e, e), f"{o}{'/' + tg if tg else ''}",
                     f(r["test"]["macro_f1"]),
                     f(ms), f(mu),
                     f"{ms - mu:+.4f}" if (ms is not None and mu is not None) else "-",
                     nsh or "-",
                     f"{r['n_test_seen_geometry']:,}",
                     f"{r['n_test_unseen_geometry']:,}"])
    if rows:
        L += ["## Test macro-F1 split by whether the geometry was seen in "
              "training", "",
              "How much of a protocol's difficulty is *unseen geometry* rather "
              "than whatever else it holds out. This matters most for "
              "`lot_time`, whose test side is a narrow slice of geometry space "
              "(see above), and it is the difference between \"forward-only "
              "time costs 20 points\" and \"forward-only deployment costs 20 "
              "points, part of it for meeting new products\".", "",
              "Both macro-F1 columns are averaged over **only the classes "
              "present in both halves**, counted in `shared classes`; the "
              "halves do not otherwise hold the same classes and their raw "
              "macro-F1 values would be averages over different class sets. "
              "Each half's full per-class F1 is in the run JSON.", "",
              table(rows, ["protocol", "representation", "objective",
                           "macro-F1 all", "seen geom. (matched)",
                           "unseen geom. (matched)", "seen - unseen",
                           "shared classes", "n seen", "n unseen"]), ""]

    # ---- does the DG negative result survive a domain that carries shift?
    dt = {k: v for k, v in SEEDS.items() if k[3] == "dtime"}
    if dt:
        def ms(v):
            """mean and half-range of test macro-F1 over the seeds present."""
            if not v:
                return None
            xs = sorted(r["test"]["macro_f1"] for r in v.values())
            return (sum(xs) / len(xs), (max(xs) - min(xs)) / 2, len(xs))

        rows = []
        for k in sorted(dt):
            p_, e, o, _ = k
            a_ = ms(SEEDS.get((p_, e, o, "")))
            b_ = ms(dt[k])
            rows.append([
                f"`{o}`", ENC_LABEL.get(e, e),
                f"{a_[0]:.4f} ±{a_[1]:.4f} (n={a_[2]})" if a_ else "-",
                f"{b_[0]:.4f} ±{b_[1]:.4f} (n={b_[2]})",
                f"{b_[0] - a_[0]:+.4f}" if a_ else "-",
                next(iter(dt[k].values())).get("n_invariance_domains", "-")])
        L += ["## Does the domain definition explain the ERM-equivalence?", "",
              "Every group-aware objective was originally handed `lot % 32` as "
              "its domain: 10,762 lots averaged into 32 buckets whose mean "
              "pairwise label total-variation is 0.0208, against 0.1666 between "
              "real lots. An invariance penalty asked to equalize distributions "
              "that are already equal is satisfied by doing nothing, so "
              "ERM-equivalence on `lot` was close to guaranteed by construction "
              "rather than discovered. `time_decile` replaces it with ten "
              "fixed, ordered, lot-level production-order groups carrying a "
              "label TV of 0.1822. One change; everything else fixed.", "",
              table(rows, ["objective", "representation",
                           "domain = `lot % 32`", "domain = production decile",
                           "difference", "n domains"]), ""]
        # the plumbing check, printed rather than trusted
        nulls = []
        for k in sorted(dt):
            if k[2] != "erm":
                continue
            base = SEEDS.get((k[0], k[1], "erm", "")) or {}
            for sd, r in dt[k].items():
                if sd in base:      # compare seed to seed, not mean to mean
                    nulls.append(abs(r["test"]["macro_f1"]
                                     - base[sd]["test"]["macro_f1"]))
        if nulls:
            L += [f"**Null control.** `erm` never reads the domain label, so "
                  f"its two columns must agree; they differ by at most "
                  f"{max(nulls):.4f}, against a measured same-code-path floor "
                  f"of about 0.002. The domain machinery did not change ERM, so "
                  f"the other rows are differences in the objective and not in "
                  f"the plumbing. If this line ever exceeds the floor, nothing "
                  f"else in the table can be read.", ""]

    # ---- the OT weight sweep: is the collapsed cell a broken method or a
    #      badly chosen default?
    sk = {k: v for k, v in R.items() if k[2] == "sinkhorn" and k[3].startswith("ot")}
    if sk:
        rows = []
        for k in sorted(sk, key=lambda k: sk[k].get("ot_lambda", 0.0)):
            r = sk[k]
            hist = [h.get("ot") for h in r["history"] if h.get("ot") is not None]
            rows.append([f"{r.get('ot_lambda')}", f(r["val_macro_f1"]),
                         f(r["test"]["macro_f1"]),
                         f(hist[0]) if hist else "-",
                         f(hist[-1]) if hist else "-"])
        best = max(sk, key=lambda k: sk[k]["val_macro_f1"])
        b = sk[best]
        base = R.get(("lot", best[1], "erm", ""))
        zero = next((v for k, v in sk.items()
                     if v.get("ot_lambda") == 0.0), None)
        L += ["## The entropic-OT objective: a broken method, or a bad default?",
              "",
              "The `sinkhorn` row in the tables above uses the default weight "
              "and sits at the majority-class floor, which would be an unfair "
              "way to conclude anything about optimal transport. This sweeps "
              "the weight over three orders of magnitude on `lot`/"
              f"{ENC_LABEL.get(best[1], best[1])}, logging the OT penalty "
              "itself so the question is not only what accuracy did but whether "
              "the penalty was ever actually reduced. Weight 0 is ERM routed "
              "through the same objective wrapper, so the comparison is not "
              "confounded by the wrapper.", "",
              table(rows, ["--ot-lambda", "val macro-F1", "test macro-F1",
                           "OT penalty, epoch 1", "epoch 12"]), ""]
        if base is not None:
            L += [f"Selecting the weight on the **domain-disjoint validation "
                  f"split** -- never on test -- picks "
                  f"{b.get('ot_lambda')}, whose test macro-F1 is "
                  f"{f(b['test']['macro_f1'])} against "
                  f"{f(base['test']['macro_f1'])} for plain ERM at the same "
                  f"encoder, protocol and seed: a difference of "
                  f"{b['test']['macro_f1'] - base['test']['macro_f1']:+.4f}.", ""]
        if zero is not None:
            zt = [h.get("ot") for h in zero["history"] if h.get("ot") is not None]
            bt = [h.get("ot") for h in b["history"] if h.get("ot") is not None]
            if zt and bt:
                L += [f"And at that selected weight the penalty ends at "
                      f"{f(bt[-1])} against {f(zt[-1])} when it is not "
                      "penalized at all -- it has not been reduced. The "
                      "objective is not being traded off against accuracy at "
                      "its best setting; it is doing nothing.", ""]
                top = max(sk.values(), key=lambda r: r.get("ot_lambda", 0.0))
                th = [h.get("ot") for h in top["history"]
                      if h.get("ot") is not None]
                if th:
                    L += ["The penalty column also shows *why* the largest "
                          "weight destroys the model, which is the part that "
                          "was previously inferred rather than seen. At "
                          f"`--ot-lambda {top.get('ot_lambda')}` the penalty "
                          f"falls {f(th[0])} -> {f(th[-1])}, essentially to "
                          "zero, while validation macro-F1 is pinned at the "
                          "majority-class floor from the first epoch and the "
                          "training loss converges to the entropy of the class "
                          "prior. The optimizer is *succeeding completely* at "
                          "the OT objective: the divergence between two domain "
                          "clouds is minimized exactly when the embedding is a "
                          "single point, and at this weight that collapse is "
                          "the global optimum of the combined loss. The "
                          "penalty is minimizable; it is just not minimizable "
                          "while the representation still carries the label.",
                          ""]
                L += ["**Verdict: not a strawman and not a tuning failure.** "
                      "Across three orders of magnitude the penalty is either "
                      "untouched (and accuracy is ERM's) or driven toward zero "
                      "(and the representation is gone). There is no weight at "
                      "which it falls and accuracy holds. Reported as a "
                      "negative result about entropic OT on this benchmark, "
                      "with the default-weight row left in the tables above so "
                      "that the collapse is visible rather than filtered.", ""]

    # ---- the acquisition-cost confound in the active-learning curve
    alb = Path("runs/al_budget_check.json")
    if alb.exists():
        d = json.loads(alb.read_text())
        B = d["curves"]["random"]["lots"]
        L += ["## The active-learning budget is in lots, and the strategies "
              "did not buy comparable data", "",
              "A lot's acquisition score is the *mean* of its wafers' scores "
              "(`scripts/active_learning.py`), and the maximum of noisy means "
              "favours small samples -- so \"take the top-scoring lots\" is "
              "partly \"take the smallest lots\". Random sampling has no such "
              "bias. The consequence is that at a fixed budget in *lots* the "
              "heuristics train on a fraction of random's wafers:", "",
              table([[s] + [f"{d['curves'][s]['wafers'][i]:,.0f}"
                            for i in range(len(B))] for s in d["curves"]],
                    ["wafers labelled"] + [f"{b} lots" for b in B]), "",
              table([[s] + [f"{d['wafers_per_lot'][s][str(b)]:.2f}" for b in B]
                     for s in d["wafers_per_lot"]],
                    ["mean wafers per lot bought"] + [f"{b} lots" for b in B]),
              ""]
        mm = d["macro_f1_at_matched_wafer_budget"]
        grid = sorted(mm["random"], key=lambda x: int(x))
        L += ["Re-plotted against wafers labelled -- the axis that was varying "
              "without being controlled -- the ranking changes. These are "
              f"{d['wafer_matched_range']['method']}:", "",
              table([[s] + [f(mm[s][g]) if mm[s][g] is not None else "-"
                            for g in grid] for s in mm],
                    ["macro-F1 at matched wafers"] + [f"{int(g):,}" for g in grid]),
              "",
              "Random leads only at the smallest point, where every strategy "
              "holds the same random seed set by construction.", ""]
        # the headline pair, computed rather than typed: the strategy's best
        # measured point, and the cheapest random point that matches it
        eff = []
        rnd = d["curves"]["random"]
        for name, cv in d["curves"].items():
            if name == "random":
                continue
            i = int(np.argmax(cv["macro_f1"]))
            best_f1, best_w = cv["macro_f1"][i], cv["wafers"][i]
            cand = [(w, f_) for w, f_ in zip(rnd["wafers"], rnd["macro_f1"])
                    if f_ >= best_f1]
            if cand:
                w_r, f_r = min(cand)
                eff.append([name, f"{best_w:,.0f}", f(best_f1), f"{w_r:,.0f}",
                            f(f_r), f"{w_r / best_w:.2f}x"])
            else:
                # random never gets there inside the measured range. Dropping
                # the row would silently delete the strongest case in the table.
                j = int(np.argmax(rnd["macro_f1"]))
                eff.append([name, f"{best_w:,.0f}", f(best_f1),
                            f"never within the measured range "
                            f"(best {f(rnd['macro_f1'][j])} at "
                            f"{rnd['wafers'][j]:,.0f})", "-", "-"])
        if eff:
            L += ["Straight from the stored table, no interpolation -- each "
                  "strategy's best measured point against the cheapest random "
                  "point that matches or beats it:", "",
                  table(eff, ["strategy", "wafers", "macro-F1",
                              "wafers random needs", "random's macro-F1",
                              "label cost ratio"]), ""]
        L += [
              "**The data-volume confound is arithmetic and certain; the "
              "reversal is not.** It rests on three seeds, interpolation "
              "between six points, and per-point standard deviations up to "
              "0.035. `scripts/al_wafer_budget.sh` re-runs the grid with the "
              "budget counted in wafers so every strategy stops at the same "
              "supervision volume. Until it lands, the claim that random "
              "acquisition beats these heuristics is **withdrawn**, not "
              "reversed.", "",
              "Both cost models are defensible and they disagree: if a "
              "metrology slot costs one lot, the lot axis is right and these "
              "heuristics waste slots on near-empty lots; if the cost is per "
              "wafer measured, the wafer axis is right. Both curves belong in "
              "the paper with the cost model named.", ""]

    # ---- active learning
    al_path = Path("runs/active_learning.json")
    if al_path.exists():
        al = json.loads(al_path.read_text())
        budgets = al["budgets"]
        rows = []
        for strat, curve in al["results"].items():
            rows.append([strat] + [f"{curve[str(b)]['macro_f1_mean']:.4f}"
                                   for b in budgets])
        L += ["## Which lots to pay to measure", "",
              "**Read this table with the section above.** The budget is in "
              "lots and the strategies bought lots of very different sizes, so "
              "these rows are not at equal supervision volume.", "",
              f"Budgets are spent in whole lots out of {al['n_pool_lots']} "
              f"available, seeded with {al['seed_lots']} random lots, "
              f"{al['seeds']} seeds. Test set is the fixed lot-disjoint split.",
              "",
              table(rows, ["strategy"] + [f"{b} lots" for b in budgets]), ""]

    # ---- SSL pretraining
    ssl_path = Path("runs/ssl_pretrain.json")
    if ssl_path.exists():
        ssl = json.loads(ssl_path.read_text())
        h = ssl["history"]
        L += ["## Lot-adversarial self-supervised pretraining", "",
              f"Masked-die modelling on {ssl['n_unlabeled']:,} unlabelled "
              f"wafers with a gradient-reversed lot head, "
              f"{ssl['minutes']:.1f} min.", "",
              table([[r["epoch"], f(r["recon_ce"]),
                      f(r.get("nuisance_ce", r.get("lot_ce"))),
                      f(r.get("nuisance_ce_chance", r.get("lot_ce_chance")))]
                     for r in h],
                    ["epoch", "masked-die CE", "nuisance CE (adversarial)",
                     "CE at chance"]),
              "",
              "The nuisance CE rising toward chance is the signal that the "
              "embedding is losing the lot's failure-rate decile and the wafer "
              "geometry. An earlier version asked the adversary to name the lot "
              "itself out of 64 hashed buckets; its loss sat at chance from "
              "epoch 1 because the label was unpredictable, so gradient "
              "reversal had nothing to reverse -- a vacuous adversary that reads "
              "as invariance in the logs.", ""]

    # ---- per-class for the best lot-protocol cell
    lot_cells = {k: v for k, v in R.items() if k[0] == "lot"}
    if lot_cells:
        # selected on the domain-disjoint *validation* split. Picking the cell
        # with the best test macro-F1 and then reporting that macro-F1 is
        # selection on the test set, and with 30-odd cells it is worth several
        # points of the number it reports.
        best_k = max(lot_cells, key=lambda k: lot_cells[k]["val_macro_f1"])
        best_test = max(lot_cells, key=lambda k: lot_cells[k]["test"]["macro_f1"])
        t = lot_cells[best_k]["test"]
        L += [f"## Per-class F1, best `lot` cell ({ENC_LABEL[best_k[1]]}, "
              f"{best_k[2]})", "",
              (f"Selected on validation macro-F1 "
               f"({lot_cells[best_k]['val_macro_f1']:.4f}); its test macro-F1 "
               f"is {t['macro_f1']:.4f}. "
               + ("Selecting on test macro-F1 instead would have picked the "
                  "same cell, so the two rules agree here and nothing is "
                  "riding on the choice."
                  if best_test == best_k else
                  f"Selecting on *test* instead would have picked "
                  f"{ENC_LABEL[best_test[1]]} / {best_test[2]}"
                  f"{'/' + best_test[3] if best_test[3] else ''} at "
                  f"{lot_cells[best_test]['test']['macro_f1']:.4f}; that is "
                  f"selection on the test set across {len(lot_cells)} cells and "
                  f"the number would be an artefact of it.")), "",
              table([[c, f(t["per_class_f1"][c])] for c in CLASSES],
                    ["class", "F1"]), "",
              "The long tail is where the shift bites: `Near-full` has 149 "
              "examples in the whole corpus and `Scratch` is a one-die-wide "
              "line, which global descriptors average away.", ""]

    Path(args.out).write_text("\n".join(L) + "\n")
    print(f"wrote {args.out} from {len(R)} cells")


if __name__ == "__main__":
    main()
