"""Regenerate RESULTS.md from runs/*.json. Nothing here is hand-typed."""
from __future__ import annotations

import sys
from pathlib import Path as _P
sys.path.insert(0, str(_P(__file__).resolve().parents[1]))

import argparse
import json
from pathlib import Path

from wts.data import CLASSES


def cell(x):
    return str(x).replace("|", "\\|")


def table(rows, header):
    out = ["| " + " | ".join(cell(h) for h in header) + " |",
           "|" + "|".join(["---"] * len(header)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(cell(c) for c in r) + " |")
    return "\n".join(out)


def f(x, n=4):
    return "-" if x is None else f"{x:.{n}f}"


def load(run_dir):
    """Benchmark cells only -- `runs/` also holds the active-learning curve, the
    RPCA lambda sweep and the pretraining history, which have their own shapes.

    Keyed by seed as well as by cell. An earlier version left the seed out of
    the key, so a second seed of a cell overwrote the first and whichever file
    sorted last won silently. Every table below either takes the reference seed
    explicitly or aggregates over the seeds it found.
    """
    out = {}
    for p in sorted(Path(run_dir).glob("*.json")):
        r = json.loads(p.read_text())
        # a cell is identified by having all three axes, not by "protocol"
        # alone: runs/ also holds the MIXED-SYNTH dataset summary and the
        # MIXED-SYNTH training results, which carry a protocol and nothing else
        # a benchmark table can use
        if not isinstance(r, dict) or not {"protocol", "encoder",
                                           "objective"} <= set(r):
            continue
        out[(r["protocol"], r["encoder"], r["objective"], r.get("tag", ""),
             r.get("seed", 0))] = r
    return out


REF_SEED = 0


def by_cell(runs):
    """(protocol, encoder, objective, tag) -> {seed: record}."""
    out = {}
    for (p, e, o, tg, sd), r in runs.items():
        out.setdefault((p, e, o, tg), {})[sd] = r
    return out


def spread(vals):
    """mean and half-range. Half-range, not a standard error: with three seeds
    an SE is a fiction, and the half-range is what you actually saw."""
    return sum(vals) / len(vals), (max(vals) - min(vals)) / 2


ENC_LABEL = {
    "feat": "size-invariant descriptors + MLP",
    "cnn_bn": "CNN on resized 64x64 (BatchNorm)",
    "cnn_gn": "CNN on resized 64x64 (GroupNorm)",
    "spectral": "spectral operator, native resolution",
    "graph": "die-graph GNN (wafer-only subgraph)",
    "rpca_cnn": "CNN + RPCA lot-signature channel",
}
TAG_LABEL = {
    "": "-",
    "rpcafeat": "+ RPCA lot signature as features",
    "fda": "+ Fourier amplitude swap augmentation",
    "sslinit": "+ lot-adversarial SSL initialization",
    "failmask": "4th channel = raw failed-die mask (RPCA control)",
    "zerochan": "4th channel = zeros (RPCA control)",
}
OBJ_NOTE = {
    "erm": "-",
    "hsic": "kernel independence testing",
    "sinkhorn": "optimal transport",
    "anchor": "econometrics / anchor regression",
    "logit_adjust": "long-tail recognition",
    "group_dro": "robust optimization",
    "dann": "domain adaptation",
    "irm": "causal inference",
    "coral": "domain adaptation",
    "mixup_domain": "vicinal risk / LISA",
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", default="runs")
    ap.add_argument("--out", default="RESULTS.md")
    args = ap.parse_args()
    runs = load(args.runs)
    if not runs:
        print("no runs yet")
        return
    SEEDS = by_cell(runs)
    # every pre-existing table is a single-seed table and is kept that way, so
    # the numbers stay comparable to what was reported before seeds were added
    R = {k: v[min(v, key=lambda sd: abs(sd - REF_SEED))] for k, v in SEEDS.items()}

    L = ["# Results", "",
         "Regenerated by `scripts/report.py` from the JSON each cell writes; no "
         "number here is typed by hand. Model selection for every cell uses a "
         "**domain-disjoint validation split carved out of the training "
         "domains** -- never the test domains.", "",
         f"Unless a table says otherwise every cell below is **seed "
         f"{REF_SEED} only**. Seed spread is not decoration on this corpus: see "
         "*Seed spread* below, where it is larger than most of the effects "
         "reported in the objective tables.", ""]

    any_run = next(iter(R.values()))
    protos = sorted({k[0] for k in R})
    L += ["## The three protocols", "",
          table([[p,
                  f(next(r["label_shift_tv"] for k, r in R.items() if k[0] == p), 4),
                  next(r["n_train"] for k, r in R.items() if k[0] == p),
                  next(r["n_val"] for k, r in R.items() if k[0] == p),
                  next(r["n_test"] for k, r in R.items() if k[0] == p)]
                 for p in protos],
                ["protocol", "label shift (TV)", "train", "val (OOD)", "test"]),
          "",
          "`iid` splits wafers at random, `lot` holds out whole lots, `size` "
          "holds out whole wafer geometries. The label marginal cannot be held "
          "fixed while holding out groups, so the shift it induces is measured "
          "rather than ignored.", ""]

    # ---- stage A
    encs = [e for e in ENC_LABEL if any(k[1] == e for k in R)]
    rows = []
    for e in encs:
        for p in protos:
            r = R.get((p, e, "erm", ""))
            if not r:
                continue
            t = r["test"]
            rows.append([ENC_LABEL[e], p, f(t["macro_f1"]), f(t["defect_macro_f1"]),
                         f(t.get("p10_domain_macro_f1")),
                         f(t.get("worst_domain_macro_f1")),
                         f(t["defect_auroc"]), f(t["ece"]),
                         f(t.get("conformal_coverage"), 3),
                         f"{r['params_m']:.2f}M", f"{r['minutes']:.1f} min"])
    if rows:
        L += ["## Representations under plain ERM", "",
              table(rows, ["representation", "protocol", "macro-F1", "defect macro-F1",
                           "p10 domain F1", "worst domain F1", "defect AUROC",
                           "ECE", "conformal cov.", "params", "wall"]), "",
              "Three caveats on the last four columns, all of which came out of "
              "reading this table adversarially rather than from a new run:", "",
              "* `p10 domain F1` and `worst domain F1` are quantized on the "
              "`lot` protocol -- see the note under the objective tables. They "
              "are informative on `size`, whose domains are large.",
              "* `ECE` is top-1 expected calibration error, weighted by sample "
              "count. 85% of this corpus is `none` and is predicted at high "
              "confidence and high accuracy, so the statistic is dominated by "
              "the easy majority and stays below 0.01 even where macro-F1 "
              "collapses. It is not a metric a model cannot game; treat it as a "
              "sanity check on the majority class only.",
              "* `conformal cov.` is built from *class-conditional* thresholds "
              "but reported as a single average over the test set, which turns "
              "it back into a marginal number that `none` dominates. "
              "`summarize` now also emits per-class coverage, the worst class, "
              "and the empty-prediction-set rate; cells measured before that "
              "change do not carry them.", ""]

    # ---- the headline gap
    gaps = []
    for e in encs:
        a, b, c = (R.get(("iid", e, "erm", "")), R.get(("lot", e, "erm", "")),
                   R.get(("size", e, "erm", "")))
        if not (a and b):
            continue
        gaps.append([ENC_LABEL[e], f(a["test"]["macro_f1"]), f(b["test"]["macro_f1"]),
                     f(a["test"]["macro_f1"] - b["test"]["macro_f1"]),
                     f(c["test"]["macro_f1"]) if c else "-",
                     f(a["test"]["macro_f1"] - c["test"]["macro_f1"]) if c else "-"])
    if gaps:
        L += ["### How much of the reported accuracy was leakage", "",
              "The gap between a random wafer split and a lot-disjoint split is "
              "the part of a published number that came from having seen the "
              "same lot in training.", "",
              table(gaps, ["representation", "iid macro-F1", "lot macro-F1",
                           "iid - lot", "size macro-F1", "iid - size"]), ""]

    # ---- stage B
    objs = [o for o in OBJ_NOTE if o != "erm" and any(k[2] == o for k in R)]
    for p in [x for x in protos if x != "iid"]:
        rows = []
        for e in encs:
            base = R.get((p, e, "erm", ""))
            if not base:
                continue
            for o in ["erm"] + objs:
                r = R.get((p, e, o, ""))
                if not r:
                    continue
                t, bt = r["test"], base["test"]
                rows.append([
                    ENC_LABEL[e], o, OBJ_NOTE[o], f(t["macro_f1"]),
                    ("-" if o == "erm"
                     else f"{t['macro_f1'] - bt['macro_f1']:+.4f}"),
                    f(t.get("p10_domain_macro_f1")),
                    ("-" if o == "erm" else
                     f"{(t.get('p10_domain_macro_f1') or 0) - (bt.get('p10_domain_macro_f1') or 0):+.4f}"),
                    f(t["per_class_f1"].get("Scratch")),
                    f(t["per_class_f1"].get("Near-full")),
                ])
        if rows:
            L += [f"## Borrowed objectives vs ERM -- protocol `{p}`", "",
                  table(rows, ["representation", "objective", "borrowed from",
                               "macro-F1", "vs ERM", "p10 domain F1",
                               "vs ERM", "Scratch F1", "Near-full F1"]), "",
                  "**Do not rank models by the `p10 domain F1` column.** A lot "
                  "holds at most 25 wafers, so a per-lot macro-F1 takes very "
                  "few distinct values -- a 25-wafer lot whose one defect is "
                  "missed scores exactly (48/49 + 0)/2 = 0.4898 whichever model "
                  "missed it. Across the cells in `runs/`, 25 separate `lot` "
                  "cells report that identical 0.4898 and 11 more report "
                  "exactly 0.5000, so the column is a discretization artefact "
                  "of lot size rather than a measure of domain robustness. "
                  "`wts.metrics.summarize` now also emits "
                  "`mean_domain_macro_f1` and `frac_domains_below_half`, which "
                  "average over ~1,700 lots and therefore do separate models; "
                  "cells measured before that change do not carry them.", ""]

    # ---- TTA
    rows = []
    for (p, e, o, tg), r in sorted(R.items()):
        for name in ("adabn", "tent", "ema"):
            key = f"test_{name}"
            if key in r:
                rows.append([p, ENC_LABEL[e], f"{o}{'/' + tg if tg else ''}", name,
                             f(r["test"]["macro_f1"]), f(r[key]["macro_f1"]),
                             f"{r[key]['macro_f1'] - r['test']['macro_f1']:+.4f}"])
    if rows:
        L += ["## Test-time adaptation and weight averaging", "",
              "`adabn` and `tent` use only the *unlabelled* test wafers -- what a "
              "fab has when a new tool comes online. `ema` is the averaged "
              "weights, a free check on whether flatness helped.", "",
              table(rows, ["protocol", "representation", "objective", "method",
                           "base macro-F1", "after", "delta"]), ""]

    # ---- tagged variants against their untagged twin
    rows = []
    for (p, e, o, tg), r in sorted(R.items()):
        if not tg:
            continue
        base = R.get((p, e, o, ""))
        t = r["test"]
        rows.append([p, ENC_LABEL[e], TAG_LABEL.get(tg, tg), f(t["macro_f1"]),
                     ("-" if not base else
                      f"{t['macro_f1'] - base['test']['macro_f1']:+.4f}"),
                     f(t.get("p10_domain_macro_f1")),
                     ("-" if not base else
                      f"{(t.get('p10_domain_macro_f1') or 0) - (base['test'].get('p10_domain_macro_f1') or 0):+.4f}")])
    if rows:
        L += ["## Variants, against the same cell without them", "",
              table(rows, ["protocol", "representation", "variant", "macro-F1",
                           "vs plain", "p10 domain F1", "vs plain"]), ""]

    # ---- seed spread, wherever more than one seed exists
    multi = {k: v for k, v in SEEDS.items() if len(v) > 1}
    if multi:
        rows = []
        for (p, e, o, tg) in sorted(multi):
            v = multi[(p, e, o, tg)]
            f1 = [r["test"]["macro_f1"] for r in sorted(v.values(),
                                                        key=lambda r: r["seed"])]
            m, hr = spread(f1)
            rows.append([p, ENC_LABEL.get(e, e), o, TAG_LABEL.get(tg, tg) if tg else "-",
                         len(v), f(m), f"+/-{hr:.4f}",
                         ", ".join(f"{x:.4f}" for x in f1)])
        L += ["## Seed spread", "",
              "Each seed reshuffles the model init *and* which training domains "
              "become the inner validation split, so this is the spread of the "
              "whole pipeline, not of the optimizer alone. It is the yardstick "
              "any claimed improvement has to clear.", "",
              table(rows, ["protocol", "representation", "objective", "variant",
                           "seeds", "mean macro-F1", "half-range", "per seed"]),
              ""]

    # ---- what the rpca_cnn fourth channel is actually worth
    abl = []
    for p in protos:
        got = {tg: SEEDS.get((p, "rpca_cnn", "erm", tg))
               for tg in ("", "failmask", "zerochan")}
        base = SEEDS.get((p, "cnn_gn", "erm", ""))
        if not got[""] or not base:
            continue
        def agg(v):
            if not v:
                return "-", "-", 0
            f1 = [r["test"]["macro_f1"] for r in v.values()]
            m, hr = spread(f1)
            return f(m), f"+/-{hr:.4f}", len(v)
        bm, bhr, bn = agg(base)
        for tg, label in ((None, "cnn_gn, 3 channels (no fourth channel)"),
                          ("", "4th = RPCA residual (the claim)"),
                          ("failmask", "4th = raw failed-die mask (control)"),
                          ("zerochan", "4th = zeros (control)")):
            v = base if tg is None else got[tg]
            if not v:
                continue
            m, hr, n = agg(v)
            delta = ("-" if tg is None else
                     f"{sum(r['test']['macro_f1'] for r in v.values()) / len(v) - sum(r['test']['macro_f1'] for r in base.values()) / len(base):+.4f}")
            abl.append([p, label, n, m, hr, delta])
    if abl:
        L += ["## What the `rpca_cnn` fourth channel is worth", "",
              "`rpca_cnn` was the best `lot` cell and the stated reason was that "
              "its fourth channel carries the wafer's defect with the lot's tool "
              "signature removed. But the per-lot RPCA returns a **rank-0** "
              "low-rank part for 94.8% of decomposed lots, and the residual it "
              "hands the encoder is bit-identical to the raw failed-die mask for "
              "95.3% of all 172,948 wafers (`scripts/ablate_sigchannel.sh`). "
              "The two controls replace that channel with the raw mask and with "
              "zeros. Read this table against *Seed spread* above.", "",
              table(abl, ["protocol", "fourth channel", "seeds",
                          "mean macro-F1", "half-range", "vs cnn_gn"]), ""]

    # ---- active learning
    al_path = Path("runs/active_learning.json")
    if al_path.exists():
        al = json.loads(al_path.read_text())
        budgets = al["budgets"]
        rows = []
        for strat, curve in al["results"].items():
            rows.append([strat] + [f"{curve[str(b)]['macro_f1_mean']:.4f}"
                                   for b in budgets])
        L += ["## Which lots to pay to measure", "",
              f"Budgets are spent in whole lots out of {al['n_pool_lots']} "
              f"available, seeded with {al['seed_lots']} random lots, "
              f"{al['seeds']} seeds. Test set is the fixed lot-disjoint split.",
              "",
              table(rows, ["strategy"] + [f"{b} lots" for b in budgets]), ""]

    # ---- SSL pretraining
    ssl_path = Path("runs/ssl_pretrain.json")
    if ssl_path.exists():
        ssl = json.loads(ssl_path.read_text())
        h = ssl["history"]
        L += ["## Lot-adversarial self-supervised pretraining", "",
              f"Masked-die modelling on {ssl['n_unlabeled']:,} unlabelled "
              f"wafers with a gradient-reversed lot head, "
              f"{ssl['minutes']:.1f} min.", "",
              table([[r["epoch"], f(r["recon_ce"]),
                      f(r.get("nuisance_ce", r.get("lot_ce"))),
                      f(r.get("nuisance_ce_chance", r.get("lot_ce_chance")))]
                     for r in h],
                    ["epoch", "masked-die CE", "nuisance CE (adversarial)",
                     "CE at chance"]),
              "",
              "The nuisance CE rising toward chance is the signal that the "
              "embedding is losing the lot's failure-rate decile and the wafer "
              "geometry. An earlier version asked the adversary to name the lot "
              "itself out of 64 hashed buckets; its loss sat at chance from "
              "epoch 1 because the label was unpredictable, so gradient "
              "reversal had nothing to reverse -- a vacuous adversary that reads "
              "as invariance in the logs.", ""]

    # ---- per-class for the best lot-protocol cell
    lot_cells = {k: v for k, v in R.items() if k[0] == "lot"}
    if lot_cells:
        # selected on the domain-disjoint *validation* split. Picking the cell
        # with the best test macro-F1 and then reporting that macro-F1 is
        # selection on the test set, and with 30-odd cells it is worth several
        # points of the number it reports.
        best_k = max(lot_cells, key=lambda k: lot_cells[k]["val_macro_f1"])
        best_test = max(lot_cells, key=lambda k: lot_cells[k]["test"]["macro_f1"])
        t = lot_cells[best_k]["test"]
        L += [f"## Per-class F1, best `lot` cell ({ENC_LABEL[best_k[1]]}, "
              f"{best_k[2]})", "",
              (f"Selected on validation macro-F1 "
               f"({lot_cells[best_k]['val_macro_f1']:.4f}); its test macro-F1 "
               f"is {t['macro_f1']:.4f}. "
               + ("Selecting on test macro-F1 instead would have picked the "
                  "same cell, so the two rules agree here and nothing is "
                  "riding on the choice."
                  if best_test == best_k else
                  f"Selecting on *test* instead would have picked "
                  f"{ENC_LABEL[best_test[1]]} / {best_test[2]}"
                  f"{'/' + best_test[3] if best_test[3] else ''} at "
                  f"{lot_cells[best_test]['test']['macro_f1']:.4f}; that is "
                  f"selection on the test set across {len(lot_cells)} cells and "
                  f"the number would be an artefact of it.")), "",
              table([[c, f(t["per_class_f1"][c])] for c in CLASSES],
                    ["class", "F1"]), "",
              "The long tail is where the shift bites: `Near-full` has 149 "
              "examples in the whole corpus and `Scratch` is a one-die-wide "
              "line, which global descriptors average away.", ""]

    Path(args.out).write_text("\n".join(L) + "\n")
    print(f"wrote {args.out} from {len(R)} cells")


if __name__ == "__main__":
    main()
