"""Regenerate WEEKEND.md from runs/*.json. Five minutes for a tired person.

    python scripts/weekend.py

Prose lives here, numbers do not. `FRIDAY` records what each headline number was
before this weekend's work; those are the values that were in `RESULTS.md` at
commit 373b9cc, and they are constants in this file only so that the *change*
can be shown. Everything in the "now" column is computed from `runs/` at write
time.
"""
from __future__ import annotations

import argparse
import json
import subprocess

import numpy as np
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from scripts.report import load as load_cells  # noqa: E402,F401

NM = "[not measured]"

# What RESULTS.md said at commit 373b9cc, Friday 11:00. Constants here so the
# before/after can be displayed; never used as if they were current results.
FRIDAY = {
    ("lot", "rpca_cnn", "erm", ""): 0.8813,
    ("lot", "cnn_gn", "erm", ""): 0.8671,
    ("lot", "cnn_bn", "erm", ""): 0.8587,
    ("lot", "spectral", "erm", ""): 0.8538,
    ("lot", "feat", "erm", ""): 0.8417,
    ("lot_time", "cnn_gn", "erm", ""): 0.6935,
    ("size", "cnn_gn", "erm", ""): 0.8203,
}


def cells(run_dir):
    out = {}
    for p in sorted(Path(run_dir).glob("*.json")):
        r = json.loads(p.read_text())
        if isinstance(r, dict) and {"protocol", "encoder", "objective"} <= set(r):
            out.setdefault((r["protocol"], r["encoder"], r["objective"],
                            r.get("tag", "")), {})[r.get("seed", 0)] = r
    return out


def agg(C, k):
    v = C.get(k)
    if not v:
        return None
    xs = sorted(r["test"]["macro_f1"] for r in v.values())
    return {"mean": sum(xs) / len(xs), "hr": (max(xs) - min(xs)) / 2,
            "n": len(xs), "vals": xs}


def show(s):
    if s is None:
        return NM
    return f"{s['mean']:.4f}" + (f" ±{s['hr']:.4f} (n={s['n']})"
                                 if s["n"] > 1 else " (n=1)")


def table(rows, header):
    return "\n".join(
        ["| " + " | ".join(map(str, header)) + " |",
         "|" + "|".join(["---"] * len(header)) + "|"]
        + ["| " + " | ".join(map(str, r)) + " |" for r in rows])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", default="runs")
    ap.add_argument("--out", default="WEEKEND.md")
    a = ap.parse_args()
    C = cells(a.runs)
    L = []
    W = L.append

    try:
        head = subprocess.run(["git", "log", "-1", "--format=%h %s"],
                              capture_output=True, text=True).stdout.strip()
    except Exception:
        head = NM

    W("# Weekend, session S1 — wafer-tool-shift")
    W("")
    W("*Regenerated by `scripts/weekend.py`; numbers computed from `runs/` at "
      f"write time. HEAD: `{head}`. Long form in `critique_log.md` and "
      "`paper_draft.md`.*")
    W("")
    W("## The short version")
    W("")
    W("Three claims this repo made on Friday are now withdrawn, all of them "
      "because of controls that had never been run. Nothing was withdrawn "
      "because of a new idea beating an old one; the weekend's output is "
      "almost entirely negative results, and they are the useful kind — each "
      "one closes off a direction that looked open.")
    W("")

    # ---------------------------------------------------------------- headline
    W("## 1. Headline numbers, Friday against now")
    W("")
    rows = []
    for k, fri in FRIDAY.items():
        s = agg(C, k)
        note = ""
        if s and s["n"] > 1:
            # FRIDAY holds the 4-dp figures as printed in RESULTS.md, so the
            # comparison is at 4 dp; an exact float compare silently never
            # matches and every row reads "one seed of this range"
            r4 = [round(v, 4) for v in s["vals"]]
            f4 = round(fri, 4)
            note = ("**Friday reported the top of this range**" if f4 == r4[-1]
                    else "Friday reported the bottom of this range"
                    if f4 == r4[0] else
                    "Friday reported one seed from inside this range"
                    if f4 in r4 else
                    "Friday's seed is not in this range (its split moved)")
        rows.append([f"`{k[0]}`", k[1], f"{fri:.4f}", show(s), note])
    W(table(rows, ["protocol", "representation", "Friday (1 seed)",
                   "now", "note"]))
    W("")
    W("**Nothing here got better, and that is the point.** The numbers moved "
      "because they acquired seeds, not because the models changed. Friday's "
      "table reported 59 cells at one seed each and no measurement of what a "
      "seed is worth.")
    W("")

    # ---------------------------------------------------------------- withdrawn
    W("## 2. What was tried, what failed, and what that rules out")
    W("")
    W("### 2.1 The RPCA lot-signature channel — withdrawn")
    W("")
    rows = []
    for p in ["lot", "lot_time", "size"]:
        base = agg(C, (p, "cnn_gn", "erm", ""))
        for tg, lab in [("", "RPCA residual (the claim)"),
                        ("failmask", "raw failed-die mask"),
                        ("zerochan", "**zeros**")]:
            s = agg(C, (p, "rpca_cnn", "erm", tg))
            if s and base:
                rows.append([f"`{p}`", lab, show(s),
                             f"{s['mean'] - base['mean']:+.4f}"])
        if base:
            rows.append([f"`{p}`", "no fourth channel", show(base), "—"])
    if rows:
        W(table(rows, ["protocol", "fourth channel", "macro-F1", "vs no channel"]))
        W("")
    W("`rpca_cnn` was the best `lot` cell at 0.8813. The RPCA low-rank part is "
      "rank 0 for 94.83% of decomposed lots and its residual is bit-identical "
      "to the raw failed-die mask for 95.27% of all wafers, so the \"lot "
      "signature channel\" is mostly a second copy of a channel the input "
      "already had. On `lot`, a fourth channel of **zeros** buys the same as "
      "the decomposition. **Rules out:** per-lot RPCA as a domain "
      "normalization on this corpus. Lots here do not share enough for the "
      "decomposition to have anything to remove.")
    W("")
    W("### 2.2 Lot-adversarial SSL pretraining — costs 5 to 8 points")
    W("")
    rows = []
    for p in ["lot", "size", "lot_time"]:
        b, s = agg(C, (p, "cnn_gn", "erm", "")), agg(C, (p, "cnn_gn", "erm", "sslinit"))
        if b and s:
            rows.append([f"`{p}`", show(b), show(s),
                         f"{s['mean'] - b['mean']:+.4f}"])
    if rows:
        W(table(rows, ["protocol", "from scratch", "SSL-initialized", "difference"]))
        W("")
        W("On every protocol the best SSL-initialized seed is below the worst "
          "from-scratch seed — the ranges do not overlap. These cells existed "
          "only as a `runs/` gap on Friday: `sweep_c.sh` built its log filename "
          "with `tr -d ' -'`, which left the slash in `--init-from "
          "runs/ssl_pretrain.pt`, so bash failed to open the redirect and the "
          "python process never started. Three cells were logged as launched "
          "and never ran, with no error anywhere a person would look.")
        W("")
        W("**Not yet a paper claim.** Every cell fine-tunes at one LR chosen "
          "for a random init, and the pretrained weights are 5.8x larger in the "
          "deepest conv. `scripts/ssl_lr_sweep.sh` runs *both* arms at four "
          "LRs. **Rules out, if it survives:** this masked-die + "
          "gradient-reversal recipe on 638,506 unlabelled wafers.")
        W("")
    W("### 2.3 The `p10 domain F1` column cannot rank models")
    W("")
    W("25 separate `lot` cells report an identical p10 of 0.489796 and 11 more "
      "report exactly 0.500000. A lot holds at most 25 wafers, so a lot whose "
      "single defect is missed scores exactly (48/49 + 0)/2 = 0.4898 whichever "
      "model missed it. The metric that was supposed to stop a model hiding a "
      "bad tool behind a good average could not separate any two models. "
      "Replaced by `mean_domain_macro_f1` and `frac_domains_below_half`, which "
      "average over ~1,700 lots. **Rules out:** per-lot worst-group statistics "
      "on domains this small, for any model comparison on this corpus.")
    W("")
    W("### 2.4 The domain-generalization negative result — withdrawn on `lot`, "
      "stands on `size`")
    W("")
    W("Every group-aware objective received `lot % 32` as its domain: 10,762 "
      "lots averaged into 32 buckets whose mean pairwise label total-variation "
      "is **0.0208**, against 0.1666 between real lots. Equalizing 32 "
      "distributions that are already equal is something every invariance "
      "penalty achieves by doing nothing, so \"no objective beats ERM on "
      "`lot`\" was close to guaranteed by construction. On `size` the same "
      "hash is not degenerate (TV 0.2592) and that column's large negative "
      "effects — GroupDRO −0.18 to −0.27 — stand.")
    W("")
    dt = [(o, agg(C, ("lot", "cnn_bn", o, "")), agg(C, ("lot", "cnn_bn", o, "dtime")))
          for o in sorted({k[2] for k in C})]
    dt = [x for x in dt if x[2]]
    if dt:
        W(table([[f"`{o}`", show(h), show(t),
                  f"{t['mean'] - h['mean']:+.4f}" if h else NM] for o, h, t in dt],
                ["objective", "domain = `lot % 32`", "domain = production decile",
                 "difference"]))
    else:
        W(f"Re-run under a domain vocabulary that carries real shift: {NM} — "
          "`scripts/domain_def_sweep.sh` is queued.")
    W("")

    alb = Path(a.runs) / "al_budget_check.json"
    if alb.exists():
        z = json.loads(alb.read_text())
        B = z["curves"]["random"]["lots"]
        i4 = B.index(400) if 400 in B else len(B) // 2
        W("### 2.4b Withdrawn: \"active learning lost to random\"")
        W("")
        W(f"At the {B[i4]}-lot budget the published table reads random "
          f"{z['curves']['random']['macro_f1'][i4]:.4f}, diverse "
          f"{z['curves']['diverse']['macro_f1'][i4]:.4f}, coreset "
          f"{z['curves']['coreset']['macro_f1'][i4]:.4f}, entropy "
          f"{z['curves']['entropy']['macro_f1'][i4]:.4f}. The same JSON records "
          "how many wafers each strategy actually labelled:")
        W("")
        W(table([[st, f"{z['curves'][st]['wafers'][i4]:,.0f}",
                  f"{z['wafers_per_lot'][st][str(B[i4])]:.2f}",
                  f"{z['wafers_relative_to_random'][st][str(B[i4])]:.1%}"]
                 for st in z["curves"]],
                [f"at {B[i4]} lots", "wafers labelled", "wafers per lot",
                 "share of random's wafers"]))
        W("")
        ent = z["curves"]["entropy"]
        j = int(np.argmax(ent["macro_f1"]))
        W("The heuristics were losing while training on a fifth of the data. "
          "A lot's acquisition score is the *mean* of its wafers' scores, and "
          "the maximum of noisy means favours small samples, so \"take the "
          "top-scoring lots\" is partly \"take the smallest lots\". Straight "
          f"from the stored table, entropy reaches {ent['macro_f1'][j]:.4f} on "
          f"{ent['wafers'][j]:,.0f} wafers, which random never reaches at any "
          "budget it was measured at. **Rules out nothing yet** — the confound "
          "is certain but the reversal rests on 3 seeds and interpolation, so "
          "the grid is being re-run with the budget in wafers.")
        W("")

    W("### 2.5 The forward-only result is a compound, not pure temporal drift")
    W("")
    tp = Path(a.runs) / "time_proxy.json"
    if tp.exists():
        d = json.loads(tp.read_text())
        sg = d.get("split_geometry", {})
        if sg:
            W(table([[f"`{k}`", v["n_geometries_train"], v["n_geometries_test"],
                      f"{v['frac_test_wafers_unseen_geometry']:.2%}"]
                     for k, v in sg.items()],
                    ["protocol", "geometries in train", "in test",
                     "test wafers of unseen geometry"]))
            W("")
            lt, lo = sg.get("lot_time", {}), sg.get("lot", {})
            W(f"`lot_time` tests on **{lt.get('n_geometries_test','?')} "
              f"geometries** against {lt.get('n_geometries_train','?')} in "
              f"training, and "
              f"{lt.get('frac_test_wafers_unseen_geometry',0):.2%} of its test "
              "wafers are of a geometry never trained on — against "
              f"{lo.get('frac_test_wafers_unseen_geometry',0):.2%} for `lot`. "
              "The forward-only drop is therefore part temporal drift and part "
              "the `size` protocol arriving through the back door. The split "
              "between the two is not yet measured and is not guessed; "
              "`run_bench.py` now evaluates the seen- and unseen-geometry "
              "halves of every test set and the backfill is the next stage to "
              "run.")
            W("")
        tv = d.get("variables", {})
        if tv:
            W("Separately, the lot numbering is **not** arbitrary: bucketing "
              "lots into deciles of lot number and correlating decile gap "
              "against distributional distance, against a null of "
              f"{d['null_draws']} reassignments of numbers to lots, gives "
              f"Spearman {tv['geometry']['spearman_gap_vs_tv']:+.4f} for "
              f"geometry (p {tv['geometry']['p_value_one_sided']:.3f}) and "
              f"{tv['failed_die_rate_ventile']['spearman_gap_vs_tv']:+.4f} for "
              "failed-die rate (p "
              f"{tv['failed_die_rate_ventile']['p_value_one_sided']:.3f}). The "
              "defect-class mix does *not* drift (p "
              f"{tv['defect_class']['p_value_one_sided']:.3f}). This kills the "
              "\"those are just arbitrary IDs\" objection but cannot separate "
              "production order from product blocking; both give this "
              "signature.")
            W("")

    det = Path(a.runs) / "determinism.json"
    if det.exists():
        dd = json.loads(det.read_text())
        W("### 2.6 Run-to-run reproducibility floor")
        W("")
        floor = dd.get("range", dd.get("run_to_run_abs_diff"))
        vals = dd.get("macro_f1_values")
        W(f"The same cell run {dd.get('n_repeats', 2)} times under identical "
          f"arguments spans **{floor:.4f}** in test macro-F1"
          + (": " + ", ".join(f"{v:.4f}" for v in vals) if vals else "")
          + ". Two cells closer together than that have not been shown to "
          "differ at all, whatever their arguments — and every verdict in "
          "`RESULTS.md` now requires the margin between two cells' seed ranges "
          "to exceed it.")
        W("")
        if dd.get("stored_inside_repeat_range") is False:
            W(f"The stored value for that cell, {dd['stored_macro_f1']:.4f}, is "
              f"**outside** those repeats — "
              f"{dd['stored_distance_to_nearest_repeat']:.4f} below the nearest, "
              "with every repeat above it. The code is not the cause: the "
              "pre-weekend code re-run on these GPUs lands inside the current "
              "range. The stored cells were measured on GPUs 2/3, which belong "
              "to another session and were not taken to check this. So total "
              "spread across sessions is roughly twice the within-session "
              "figure, and the seed spreads quoted elsewhere understate it "
              "because a cell's seeds are all run back-to-back on one pair of "
              "devices. `scripts/backfill_metrics.sh` refuses to overwrite "
              "measured cells while that is true.")
        W("")

    lb = Path(a.runs) / "label_blind.json"
    if lb.exists():
        d = json.loads(lb.read_text())
        W("### 2.7 Closed without a run: the label-aware split guard never fires")
        W("")
        W("Both external reviewers flagged that `_stratified_group_split` reads "
          "candidate groups' labels to decide what may be held out. Dropping "
          "the guard entirely and comparing the partitions, no model involved:")
        W("")
        W(table([[f"`{k}`", f"{v['seeds_where_guard_fired']} / {d['seeds']}",
                  f"{v['seeds_where_split_differs']} / {d['seeds']}",
                  f"{v['seeds_where_blind_loses_a_class']} / {d['seeds']}"]
                 for k, v in d["protocols"].items()],
                ["protocol", "seeds where the guard fired",
                 "seeds where the split differed",
                 "seeds where label-blind lost a class"]))
        W("")
        mx = max(v["max_share_in_one_lot"]
                 for v in d["class_concentration"].values())
        W("The bias is not small, it is zero: the partitions are identical "
          "wafer for wafer at every seed. Structurally so — the guard rejects a "
          "group only if that group holds *all* remaining training examples of "
          f"some class, and no lot holds more than {mx:.2%} of any class. The "
          "code path is label-aware; the split is not. This was in last "
          "revision's decision list on the strength of two reviewers agreeing; "
          "four minutes of CPU would have settled it first.")
        W("")

    # ---- the handed-down target, answered with numbers
    mx = sorted(Path(a.runs).glob("mixedsynth__*.json"))
    if mx:
        import collections as _c
        G = _c.defaultdict(list)
        for p_ in mx:
            r = json.loads(p_.read_text())
            G[(r["protocol"], r["loss"])].append(r)
        W("### 2.8 The target, answered: 0.95 is not reachable here and focal "
          "is not the reason")
        W("")
        rows = []
        for proto, label in (("iid", "optimistic (random source split)"),
                             ("lot", "honest (lot-disjoint sources)")):
            best, bl = None, None
            for (pp, loss), rs in G.items():
                if pp != proto:
                    continue
                v = sum(r["test_at_val_tuned_thresholds"]["macro_f1"]
                        for r in rs) / len(rs)
                if best is None or v > best:
                    best, bl = v, loss
            rows.append([label, f"`{bl}`", f"{best:.4f}", f"{best - 0.95:+.4f}"])
        W(table(rows, ["protocol", "best loss", "multi-label macro-F1",
                       "vs the 0.95 target"]))
        W("")
        def _vals(k):
            return sorted(r["test_at_val_tuned_thresholds"]["macro_f1"]
                          for r in G[k])
        overlaps = all(
            not (min(_vals((p_, "focal"))) > max(_vals((p_, "bce")))
                 or min(_vals((p_, "bce"))) > max(_vals((p_, "focal"))))
            for p_ in ("iid", "lot"))
        W("Measured on **MIXED-SYNTH**, which is synthetic — mixed-type wafers "
          "built by OR-ing two same-geometry WM-811K wafers — and therefore an "
          "*upper bound* on the real mixed-type task, since overlaid patterns "
          "do not interact the way compound defects do. So the closest figure "
          "to the target is the optimistic split of an easier-than-real "
          "dataset, and it still misses by more than a tenth."
          + (" Focal's seed range overlaps plain BCE's on both protocols, and "
             "positive-class weighting is clearly worse: the loss named in the "
             "target contributes nothing." if overlaps else ""))
        W("")

    # ---------------------------------------------------------------- decisions
    W("## 3. Four things that need a human decision")
    W("")
    W("**Decision 1 — MixedWM38, or drop the multi-label target.** The target "
      "says \"multi-label F1 ≥ 0.95\". WM-811K is single-label over 9 classes, "
      "so that number is not defined on it. MixedWM38 could not be acquired "
      "from this machine: the HuggingFace copy (`wafervqaanon/MixedWM38-VQA`) "
      "is gated behind manual approval and Zenodo 10.5281/zenodo.20061545 "
      "returns HTTP 403 on its files. Options:")
    W("")
    W("  - **(a)** Give the box Kaggle credentials (`~/.kaggle/kaggle.json`) or "
      "request access to the gated HuggingFace copy, and the multi-label number "
      "becomes measurable on the real benchmark. One human action.")
    W("  - **(b)** Accept **MIXED-SYNTH** — built this weekend, overlaid "
      "WM-811K patterns, lot-disjoint, labelled synthetic in every artefact — "
      "and report it as an *upper bound*, because overlaid patterns do not "
      "interact the way real compound defects do.")
    W("  - **(c)** Drop the multi-label target as not well posed on this corpus "
      "and report 9-class macro-F1 instead, stating why.")
    W("")
    W("  *Recommendation: (a) if anyone can spare five minutes for the "
      "credentials, else (b) with the upper-bound caveat kept prominent.*")
    W("")
    W("**Decision 2 — what to do about the 0.95 target, now that it is "
      "measured.** Section 2.8 gives the multi-label numbers and section 1 the "
      "single-label ones; every reading misses, and the closest is the "
      "optimistic split of a synthetic upper bound. The best lot-disjoint cell is "
      f"{show(agg(C, ('lot', 'cnn_gn', 'erm', '')))} and the best iid cell is "
      f"{show(agg(C, ('iid', 'cnn_gn', 'erm', '')))}. Published figures near "
      "0.95 are 9-class iid splits with heavy augmentation, which is the `iid` "
      "column and a different quantity. Options: **(a)** keep the "
      "lot-disjoint number as the headline and report the gap to the "
      "optimistic protocol as the contribution; **(b)** chase 0.95 on `iid` "
      "with augmentation and a bigger backbone, and report it clearly as the "
      "optimistic protocol. *Recommendation: (a). The gap is the paper; "
      "closing it by loosening the split is the one thing the rules here "
      "forbid.*")
    W("")
    W("**Decision 4 — which acquisition cost model is the real one?** The "
      "active-learning comparison depends entirely on it and the two answers "
      "disagree. If a metrology slot costs one **lot** whatever its size, the "
      "published lot-budget curve is right and the finding is that these "
      "heuristics waste slots on near-empty lots. If the cost is per **wafer "
      "measured**, the wafer axis is right and the heuristics are ahead of "
      "random. Measured in a smoke run of the new code: to acquire ~780 "
      "wafers, random needed 50 lots and entropy needed 360 — same data, seven "
      "times the slots. *Recommendation: state the fab's actual cost model and "
      "report the curve for it, with the other beside it. This is the one "
      "question here that only someone who knows the metrology contract can "
      "answer.*")
    W("")
    W("**Decision 3 — how should the forward-only result be framed?** It is "
      "the repo's largest number and it is a compound. `lot_time` tests on a "
      "narrow geometry slice with a seventh of its wafers of geometries never "
      "trained on (section 2.5), so \"forward-only *time* costs 20 points\" "
      "is not what was measured. Options: **(a)** reframe it as *forward-only "
      "deployment* — you meet new products and new tools going forward, and "
      "the geometry shift is part of the phenomenon, not a confound to remove; "
      "**(b)** build a geometry-controlled temporal protocol that holds the "
      "geometry mix fixed across the time boundary, isolating drift but "
      "measuring something a fab never actually experiences; **(c)** report "
      "both. *Recommendation: (a) as the headline with the decomposition "
      "printed beside it. A fab does not get to hold its product mix fixed, so "
      "(b) measures a cleaner quantity that matters less. The decomposition "
      "that makes (a) honest is queued and is the next stage to land.*")
    W("")

    # ---------------------------------------------------------------- running
    W("## 4. What is still running, and how to check it")
    W("")
    W("Stages run one at a time on GPUs 0 and 1: `scripts/chain_s1.sh` then "
      "`scripts/chain_rest.sh`, which waits on a marker line in the previous "
      "stage's log. Nothing runs in parallel with anything else, so a stage "
      "that hangs stops the queue rather than oversubscribing the two leased "
      "devices.")
    W("")
    W("```")
    W("tail -f logs/chain_s1.log      # which stage is up")
    W("nvidia-smi                     # devices 0,1 only; 2,3 belong to another loop")
    W("ls -t runs/*.json | head       # newest cells")
    W("python scripts/report.py && python scripts/paper.py && python scripts/weekend.py")
    W("python tests/run_tests.py      # no pytest in the pdeno env, by design")
    W("```")
    W("")
    # order matches scripts/chain_s1.sh then scripts/chain_rest.sh
    stages = [
        ("`sinkhorn_lambda.sh`", "logs/sinkhorn_lambda.log",
         "7 OT weights incl. 0 as an ERM control through the same wrapper, "
         "with the penalty itself logged. **Answered**: tuned on validation it "
         "is +0.0004 over ERM and the penalty is never reduced -- inert, not a "
         "tradeoff"),
        ("`domain_def_sweep.sh`", "logs/domain_def.log",
         "7 objectives x {lot%32, production decile} x 3 seeds. The headline "
         "re-test: does the DG negative result survive a domain definition "
         "that carries real shift?"),
        ("`backfill_metrics.sh`", "logs/backfill.log",
         "the seen/unseen-geometry decomposition on every ERM cell -- how much "
         "of the forward-only drop is geometry rather than time -- plus the "
         "metrics added since these cells ran. Measures the run-to-run floor "
         "first and **refuses to overwrite** anything if stored values do not "
         "reproduce within it"),
        ("`mixed_sweep.sh`", "logs/mixed_sweep.log",
         "MIXED-SYNTH, 3 losses incl. focal, both protocols, 2 seeds"),
        ("`ssl_lr_sweep.sh`", "logs/ssl_lr.log",
         "both arms at 3 more LRs; the confound check on the -5 to -8 point "
         "SSL result"),
        ("`longtail_sweep.sh`", "logs/longtail.log",
         "focal gamma over {0, 0.5, 1, 2, 5} plus class weighting, 2 seeds; "
         "gamma=0 is bit-exact ERM and is the built-in control"),
    ]
    rows = []
    for name, log, what in stages:
        p = Path(log)
        if not p.exists():
            st = "queued"
        else:
            txt = p.read_text()
            st = "done" if "done ===" in txt else "running"
        rows.append([name, st, f"`{log}`", what])
    W(table(rows, ["stage", "status", "log", "what it decides"]))
    W("")
    W("Nothing writes outside this repository, nothing touches GPUs 2 or 3, and "
      "no package was installed into any shared environment. `runs.bak_*/` is a "
      "copy of `runs/` as it stood on Friday, gitignored, kept so any re-run "
      "can be checked against what it replaced.")
    W("")

    Path(a.out).write_text("\n".join(L) + "\n")
    print(f"wrote {a.out} from {len(C)} cells")


if __name__ == "__main__":
    main()
