"""Regenerate WEEKEND.md from runs/*.json. Five minutes for a tired person.

    python scripts/weekend.py

Prose lives here, numbers do not. `FRIDAY` records what each headline number was
before this weekend's work; those are the values that were in `RESULTS.md` at
commit 373b9cc, and they are constants in this file only so that the *change*
can be shown. Everything in the "now" column is computed from `runs/` at write
time.
"""
from __future__ import annotations

import argparse
import json
import subprocess

import numpy as np
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from scripts.report import (floor_for, floors,  # noqa: E402,F401
                            load as load_cells)

NM = "[not measured]"

# What RESULTS.md said at commit 373b9cc, Friday 11:00. Constants here so the
# before/after can be displayed; never used as if they were current results.
FRIDAY = {
    ("lot", "rpca_cnn", "erm", ""): 0.8813,
    ("lot", "cnn_gn", "erm", ""): 0.8671,
    ("lot", "cnn_bn", "erm", ""): 0.8587,
    ("lot", "spectral", "erm", ""): 0.8538,
    ("lot", "feat", "erm", ""): 0.8417,
    ("lot_time", "cnn_gn", "erm", ""): 0.6935,
    ("size", "cnn_gn", "erm", ""): 0.8203,
}


def cells(run_dir):
    out = {}
    for p in sorted(Path(run_dir).glob("*.json")):
        r = json.loads(p.read_text())
        if isinstance(r, dict) and {"protocol", "encoder", "objective"} <= set(r):
            out.setdefault((r["protocol"], r["encoder"], r["objective"],
                            r.get("tag", "")), {})[r.get("seed", 0)] = r
    return out


def agg(C, k):
    v = C.get(k)
    if not v:
        return None
    xs = sorted(r["test"]["macro_f1"] for r in v.values())
    return {"mean": sum(xs) / len(xs), "hr": (max(xs) - min(xs)) / 2,
            "n": len(xs), "vals": xs}


def show(s):
    if s is None:
        return NM
    return f"{s['mean']:.4f}" + (f" ±{s['hr']:.4f} (n={s['n']})"
                                 if s["n"] > 1 else " (n=1)")


def table(rows, header):
    return "\n".join(
        ["| " + " | ".join(map(str, header)) + " |",
         "|" + "|".join(["---"] * len(header)) + "|"]
        + ["| " + " | ".join(map(str, r)) + " |" for r in rows])


def sep(xs, base, floor):
    """Do two cells differ? Ranges must not overlap AND the margin must clear
    the run-to-run floor. Returns (verdict, margin)."""
    if not xs or not base or len(xs) < 2 or len(base) < 2:
        return "no error bar", None
    if min(xs) > max(base):
        m = min(xs) - max(base)
    elif min(base) > max(xs):
        m = -(min(base) - max(xs))
    else:
        return "overlaps", 0.0
    if floor is None:
        return f"disjoint by {abs(m):.4f}", m
    return (("**clears the floor**" if abs(m) > floor
             else f"below the floor ({abs(m):.4f} < {floor:.4f})"), m)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", default="runs")
    ap.add_argument("--out", default="WEEKEND.md")
    a = ap.parse_args()
    C = cells(a.runs)
    R = lambda n: Path(a.runs) / n
    js = lambda n: json.loads(R(n).read_text()) if R(n).exists() else None
    L = []
    W = L.append

    try:
        head = subprocess.run(["git", "log", "-1", "--format=%h %s"],
                              capture_output=True, text=True).stdout.strip()
    except Exception:
        head = NM

    det = js("determinism.json")
    # per protocol, not one number: `size` is two and a half times `lot`
    F = floors(a.runs)
    floor = F.get("_fallback")

    W("# Weekend, session S1 — wafer-tool-shift")
    W("")
    W("*Generated by `scripts/weekend.py`; every number computed from `runs/` "
      f"at write time. HEAD `{head}`. Long form: `critique_log.md` (numbered "
      "entries) and `paper_draft.md`.*")
    W("")

    # ---------------------------------------------------------------- summary
    W("## Read this first")
    W("")
    meas = {k: v for k, v in F.items() if k != "_fallback"}
    if meas:
        W("**Identical invocations of one cell do not give the same number, and "
          "the spread is larger than most of the effects the Friday tables "
          "reported as findings.** Measured by re-running one cell several "
          "times per protocol: "
          + ", ".join(f"`{k}` {v:.4f}" for k, v in sorted(meas.items()))
          + ". It is not one number — `size` is two and a half times `lot` — "
          "and protocols without their own measurement are judged against the "
          "largest, because being too strict withdraws a claim and being too "
          "lenient publishes one.")
        W("")
        W("**Two standards are used below and it matters which you are "
          "reading.** Most tables here hold dozens of cells at three seeds, "
          "where a p-value is unavailable at any effect size — an exact "
          "permutation test with three per arm has twenty arrangements and a "
          "smallest attainable two-sided p of 0.1. Those tables ask whether "
          "the seed ranges are disjoint and the margin clears the floor. That "
          "is a **screen, not a verdict**: a sample's range grows with the "
          "sample, so it becomes stricter as evidence accumulates, and at eight "
          "seeds it calls an effect with p = 0.0005 *overlapping*. Where a "
          "comparison has been run properly — eight seeds per arm — the "
          "permutation test is reported and is the one to believe.")
        W("")
    W("Most of what follows is a withdrawal. Six claims the repository made on "
      "Friday do not survive being measured against that floor, and none was "
      "withdrawn because a new idea beat an old one. Each closes off a "
      "direction that looked open, and two of them — the acquisition cost "
      "model and the forward-only decomposition — replace a wrong answer with "
      "a better question.")
    W("")
    W("**Two things did come out positive, and both were controlled.** Changing "
      "what the encoder pools moved the long tail (section 2.0), and it is the "
      "one actionable result here. GroupNorm over BatchNorm survived being "
      "re-measured with a test capable of resolving it (section 3).")
    W("")
    W("Nothing here was obtained by loosening a protocol. Where a protocol "
      "changed, both numbers are reported and neither is discarded.")
    W("")

    # ---------------------------------------------------------------- headline
    W("## 1. Headline numbers, Friday against now")
    W("")
    rows = []
    for k, fri in FRIDAY.items():
        s = agg(C, k)
        note = ""
        if s and s["n"] > 1:
            r4 = [round(v, 4) for v in s["vals"]]
            f4 = round(fri, 4)
            note = ("**Friday reported the top of this range**" if f4 == r4[-1]
                    else "Friday reported the bottom of this range"
                    if f4 == r4[0] else
                    "Friday reported one seed from inside this range"
                    if f4 in r4 else
                    "Friday's seed is not in this range")
        rows.append([f"`{k[0]}`", k[1], f"{fri:.4f}", show(s), note])
    W(table(rows, ["protocol", "representation", "Friday (1 seed)", "now",
                   "note"]))
    W("")
    W("Nothing got better. The numbers moved because they acquired seeds, not "
      "because the models changed. Friday's table was 59 cells at one seed "
      "each with no measurement of what a seed was worth.")
    W("")
    if det and det.get("stored_inside_repeat_range") is False:
        W(f"A further caution on that table: repeating one of those cells "
          f"{det['n_repeats']} times gives "
          + ", ".join(f"{v:.4f}" for v in det["macro_f1_values"])
          + f", and the stored Friday value {det['stored_macro_f1']:.4f} sits "
          f"**outside** all of them, {det['stored_distance_to_nearest_repeat']:.4f} "
          "below the nearest. The pre-weekend code re-run on these GPUs lands "
          "inside the current range, so the code is not the cause; the Friday "
          "cells were measured on GPUs 2/3, which belong to another session "
          "and were not taken to check. Spread *across* sessions is therefore "
          "about twice the within-session figure, and seed spread understates "
          "it because a cell's seeds are always run back to back.")
        W("")

    # ---------------------------------------------------------------- positive
    P = {t: {sd: r for sd, r in v.items()}
         for t, v in ((t, C.get(("lot", "cnn_gn", "erm", t), {}))
                      for t in ("poolmean", "poolmeanmax", "poolmeanmean"))
         if v}
    if len(P) == 3:
        W("## 2.0 The one thing that worked: what the encoder pools")
    W("")
    pall = {}
    for proto in ("iid", "lot", "lot_time", "size"):
        for fn, lab in ((f"pooling_{proto}_perm_macro_f1.json", "macro-F1"),
                        (f"pooling_{proto}_perm_class_Scratch.json", "Scratch"),
                        (f"pooling_{proto}_perm.json", "macro-F1"),
                        (f"pooling_{proto}_perm_scratch.json", "Scratch")):
            d_ = js(fn)
            if d_ and (proto, lab) not in pall:
                pall[(proto, lab)] = d_
        W("")
        bx = sorted(r["test"]["macro_f1"] for r in P["poolmean"].values())
        bsc = sorted(r["test"]["per_class_f1"]["Scratch"]
                     for r in P["poolmean"].values())
        rows = []
        for t, lab in (("poolmean", "`mean` — global average, the original"),
                       ("poolmeanmax", "`meanmax` — **treatment**"),
                       ("poolmeanmean", "`meanmean` — **capacity control**")):
            xs = sorted(r["test"]["macro_f1"] for r in P[t].values())
            sc = sorted(r["test"]["per_class_f1"]["Scratch"]
                        for r in P[t].values())
            rows.append([
                lab, f"{sum(xs)/len(xs):.4f} (n={len(xs)})",
                "—" if t == "poolmean" else f"{sum(xs)/len(xs)-sum(bx)/len(bx):+.4f}",
                "—" if t == "poolmean" else sep(xs, bx, floor)[0],
                f"{sum(sc)/len(sc):.4f}",
                "—" if t == "poolmean" else f"{sum(sc)/len(sc)-sum(bsc)/len(bsc):+.4f}",
                "—" if t == "poolmean" else sep(sc, bsc, floor)[0]])
        W(table(rows, ["pooling", "macro-F1", "vs `mean`", "verdict",
                       "Scratch F1", "vs `mean`", "verdict"]))
        W("")
        perm = {}
        for fn, lab in (("pooling_lot_perm.json", "macro-F1"),
                        ("pooling_lot_perm_scratch.json", "Scratch F1")):
            d = js(fn)
            if d:
                perm[lab] = d
        if perm:
            W("**Ignore the `verdict` columns above and read this table "
              "instead.** Those verdicts ask whether the seed ranges overlap, "
              "which is the right default for a table of three-seed cells and "
              "the wrong tool once a comparison has been run properly — a "
              "sample's range grows with the sample, so more seeds make "
              "non-overlap strictly harder. An exact permutation test does not "
              "punish extra data:")
            W("")
            W(table([[lab, d["n_per_arm"], f"{d['difference']:+.4f}",
                      d["range_test"]["verdict"],
                      f"**{d['permutation_test']['p_two_sided']:.5f}**"]
                     for lab, d in perm.items()],
                    ["metric", "seeds/arm", "difference", "range test",
                     "exact permutation p"]))
            W("")
            W("The effect is concentrated in `Scratch`, at a p more than twenty "
              "times smaller than macro-F1's — which is what the mechanism "
              "predicts, and it was predicted before the run rather than "
              "observed after it. The range test calling this *overlaps* at "
              "p = 0.0005 is the clearest illustration in this repository of "
              "why the criterion used elsewhere is a floor and not a verdict.")
            W("")
        if pall:
            W("**Across all four protocols, eight seeds per arm.** This is the "
              "shape of the finding and it is not the macro-F1 row:")
            W("")
            W(table([[f"`{k[0]}`", k[1], f"{d['difference']:+.4f}",
                      f"**{d['permutation_test']['p_two_sided']:.5f}**"]
                     for k, d in sorted(pall.items())],
                    ["protocol", "metric", "vs `mean`", "exact permutation p"]))
            W("")
            W("`Scratch` improves on **every protocol where the test wafers "
              "share their geometry with training** — `iid` at 99.95% shared, "
              "`lot` at 99.7%, `lot_time` at 86% — each at p ≤ 0.001, and it "
              "fails only on `size`, which holds geometry out entirely. "
              "macro-F1 follows where one class can move a nine-class average "
              "and does not on `lot_time`, where it cannot. A max over a "
              "resampled feature map depends on the die density of the wafer "
              "it came from, so the statistic that recovers a thin structure "
              "is the one that does not transfer across geometry.")
            W("")
        W("`CnnResized.embed` was a global average over the final feature map. "
          "A `Scratch` is a thin connected line; averaged over the wafer it is "
          "close to a slightly elevated background failure rate, which is "
          "exactly the statistic that discards the fact that the failures form "
          "a line. Concatenating a max recovers it.")
        W("")
        W("**`meanmean` is why this is a result and not a number.** It has "
          "`meanmax`'s exact parameter count and carries the mean concatenated "
          "with itself, so it separates \"max pooling helps\" from \"a wider "
          "head helps\". It buys nothing. The RPCA channel died on precisely "
          "this question, asked after the fact; here it was asked first.")
        W("")
        W("Three other explanations for the long tail were measured and "
          "discarded first: focal loss over five values of gamma against its "
          "own bit-exact `gamma = 0` control, class-balanced weighting, and "
          "input resolution — the last refuted outright, since 97.7% of wafers "
          "are *upsampled* to reach 64x64 and a finer grid has nothing to "
          "recover. **The long tail was an architecture problem, not a class-"
          "imbalance problem.** That is the sentence worth taking away.")
        W("")
        W("*Caveat, and it is the one this repository would insist on: this is "
          "measured on `lot` with one encoder. A benchmark whose thesis is that "
          "results move when the protocol changes should not report a "
          "single-protocol win. `iid`, `size` and `lot_time` are running.*")
        W("")

    # ---------------------------------------------------------------- withdrawn
    W("## 2. What was withdrawn, and what each withdrawal rules out")
    W("")

    W("### 2.1 \"No borrowed DG objective beats ERM\" — the experiment could "
      "not have shown otherwise, and the conclusion survives anyway")
    W("")
    tv = (js("corpus_stats.json") or {}).get("domain_label_tv", {})
    if tv:
        W("Every group-aware objective was handed `lot % 32` as its domain: "
          f"{tv.get('real_lots', {}).get('n_groups_total', '?'):,} lots "
          "averaged into 32 buckets. Mean pairwise label total-variation "
          f"between those buckets is **"
          f"{tv['hash32_lot']['mean_pairwise_label_tv']:.4f}**, against "
          f"{tv['real_lots']['mean_pairwise_label_tv']:.4f} between real lots "
          f"and {tv['time_decile']['mean_pairwise_label_tv']:.4f} between "
          "production-order deciles. An invariance penalty asked to equalize "
          "distributions that are already equal is satisfied by doing nothing.")
        W("")
    dt = sorted({k[2] for k in C if k[3] == "dtime"})
    if dt:
        rows = []
        for o in dt:
            base = agg(C, ("lot", "cnn_bn", "erm", "dtime"))
            x = agg(C, ("lot", "cnn_bn", o, "dtime"))
            if not (base and x) or o == "erm":
                continue
            v, _ = sep(x["vals"], base["vals"], floor)
            rows.append([f"`{o}`", show(x), f"{x['mean'] - base['mean']:+.4f}",
                         v])
        if rows:
            W("Re-run against production deciles — nine times the label shift "
              "— with every objective compared to ERM measured under the *same* "
              "domain definition:")
            W("")
            W(table(rows, ["objective", "macro-F1", "vs ERM", "verdict"]))
            W("")
            W("**None of them beats ERM.** So the original claim was unearned "
              "and its direction was right: the experiment as run could not "
              "have shown otherwise, and the corrected experiment agrees that "
              "nothing helps.")
            W("")
            dg = js("dg_power_check.json")
            if dg:
                W("**But \"nothing is distinguishable from ERM\" was wrong, "
                  "and it was wrong because three seeds cannot see it.** The "
                  "two largest effects, taken to eight seeds per arm and read "
                  "with an exact permutation test:")
                W("")
                W(table([[f"`{v['objective']}`", v["n_per_arm"],
                          f"{v['difference']:+.4f}",
                          "ranges overlap" if v["ranges_overlap"]
                          else "ranges disjoint",
                          f"**{v['p_two_sided']:.5f}**"] for v in dg.values()],
                        ["objective", "seeds/arm", "vs ERM", "range screen",
                         "exact permutation p"]))
                W("")
                W("Both are **significantly worse than ERM**. The corrected "
                  "claim is that none of the borrowed objectives helps, two are "
                  "established as actively harmful under a domain definition "
                  "that carries real shift, and four are genuinely "
                  "unestablished at this seed budget. That is a better result "
                  "than the null it replaces: a uniformly null table cannot "
                  "show that the benchmark would detect a harmful method if one "
                  "existed, and this does. **Rules out:** this family of "
                  "invariance objectives on this corpus, now with evidence "
                  "rather than with silence.")
                W("")
            sz = {o: (agg(C, ("size", "cnn_bn", o, "sizeseed")),
                      agg(C, ("size", "cnn_bn", "erm", "sizeseed")))
                  for o in ("group_dro", "logit_adjust")}
            if all(a and b for a, b in sz.values()):
                fl_sz = floor_for(F, "size") if False else None
                fs = js("determinism__size__cnn_bn.json")
                fsz = fs.get("range") if fs else None
                W("**And the `size` protocol, which was the half of this result "
                  "said to 'stand', does not stand either.** It was the only "
                  "place a borrowed objective showed a large effect, and those "
                  "cells were single-seed. Re-run at three seeds in one "
                  "session, with `size`'s own run-to-run floor measured first "
                  f"({fsz:.4f}, two and a half times `lot`'s):")
                W("")
                rows2 = []
                for o, (x, b) in sz.items():
                    v, m = sep(x["vals"], b["vals"], fsz)
                    rows2.append([f"`{o}`", f"{x['mean'] - b['mean']:+.4f}",
                                  f"{max(x['vals']) - min(x['vals']):.4f}", v])
                W(table(rows2, ["objective", "vs ERM on `size`",
                                "its own seed range", "verdict"]))
                W("")
                W("GroupDRO's mean effect is the largest number in this "
                  "repository and it still fails: its seeds span more than its "
                  "effect, so its range and ERM's overlap almost exactly. It is "
                  "not a method that loses on geometry shift; it is a method "
                  "that is *unstable* on geometry shift. **Rules out:** this "
                  "family of invariance objectives, on this corpus, on either "
                  "protocol, under either domain definition — with no exception "
                  "left.")
                W("")

    alb = js("al_budget_check.json")
    if alb:
        B = alb["curves"]["random"]["lots"]
        i4 = B.index(400) if 400 in B else len(B) // 2
        W("### 2.2 \"Active learning lost to random\" — it lost while training "
          "on a fifth of the data")
        W("")
        W(table([[s_, f"{alb['curves'][s_]['wafers'][i4]:,.0f}",
                  f"{alb['wafers_per_lot'][s_][str(B[i4])]:.2f}",
                  f"{alb['wafers_relative_to_random'][s_][str(B[i4])]:.1%}"]
                 for s_ in alb["curves"]],
                [f"at a {B[i4]}-lot budget", "wafers labelled",
                 "wafers per lot", "share of random's"]))
        W("")
        W("The budget was counted in lots. A lot's acquisition score is the "
          "*mean* of its wafers' scores, and the maximum of noisy means favours "
          "small samples, so \"take the top-scoring lots\" is substantially "
          "\"take the smallest lots\".")
        W("")
    alw = js("active_learning_wafers.json")
    if alw:
        Bw, Rw = alw["budgets"], alw["results"]
        W("Re-run with the budget in **wafers**, so every strategy stops at the "
          "same supervision volume:")
        W("")
        W(table([[s_] + [f"{Rw[s_][str(b)]['macro_f1_mean']:.4f}" for b in Bw]
                 for s_ in Rw],
                ["macro-F1"] + [f"{b:,} wafers" for b in Bw]))
        W("")
        W(table([[s_] + [f"{Rw[s_][str(b)]['lots_mean']:,.0f}" for b in Bw]
                 for s_ in Rw],
                ["lots it took"] + [f"{b:,}" for b in Bw]))
        W("")
        ent_c, rnd_c = Rw["entropy"], Rw["random"]
        top_b = str(Bw[-1])
        W(f"The ranking reverses: entropy reaches "
          f"{ent_c[top_b]['macro_f1_mean']:.4f} against random's "
          f"{rnd_c[top_b]['macro_f1_mean']:.4f} at {Bw[-1]:,} wafers, and "
          "leads at every budget. **But it needs "
          f"{ent_c[top_b]['lots_mean'] / rnd_c[top_b]['lots_mean']:.1f}x the metrology "
          "slots for the same measured wafers.** Neither result is a fact "
          "about active learning; both are facts about active learning plus a "
          "cost model that was never stated. **Rules out:** reporting either "
          "curve alone. See Decision 4.")
        W("")

    W("### 2.3 Our own two contributions, and one of our own metrics")
    W("")
    cs = js("corpus_stats.json") or {}
    rp = cs.get("rpca")
    sub = []
    for p_ in ("lot",):
        base = agg(C, (p_, "cnn_gn", "erm", ""))
        for tg, lab in (("", "RPCA residual (the claim)"),
                        ("failmask", "raw failed-die mask"),
                        ("zerochan", "**zeros**")):
            x = agg(C, (p_, "rpca_cnn", "erm", tg))
            if x and base:
                v, _ = sep(x["vals"], base["vals"], floor)
                sub.append([lab, show(x), f"{x['mean'] - base['mean']:+.4f}", v])
        if base:
            sub.append(["no fourth channel", show(base), "—", "—"])
    if sub:
        W("**The RPCA lot-signature channel.** "
          + (f"Its low-rank part is rank 0 for "
             f"{rp['frac_rank0_of_decomposed']:.1%} of decomposed wafers and "
             f"the residual it hands the encoder is bit-identical to the raw "
             f"failed-die mask for {rp['frac_residual_identical_to_failmask']:.1%} "
             "of all wafers. " if rp else "")
          + "On `lot`:")
        W("")
        W(table(sub, ["fourth channel", "macro-F1", "vs 3-channel", "verdict"]))
        W("")
        W("A channel of **zeros** buys what the decomposition buys. **Rules "
          "out:** per-lot RPCA as a domain normalization here — lots do not "
          "share enough for it to have anything to remove.")
        W("")
    rows = []
    for p_ in ("lot", "size", "lot_time"):
        b, s = agg(C, (p_, "cnn_gn", "erm", "")), agg(C, (p_, "cnn_gn", "erm", "sslinit"))
        if b and s:
            v, _ = sep(s["vals"], b["vals"], floor)
            rows.append([f"`{p_}`", show(b), show(s),
                         f"{s['mean'] - b['mean']:+.4f}", v])
    if rows:
        W("**Lot-adversarial SSL pretraining** on 638,506 unlabelled wafers:")
        W("")
        W(table(rows, ["protocol", "from scratch", "SSL-initialized", "delta",
                       "verdict"]))
        W("")
        lrs = []
        for lr in ("2e-4", "5e-4", "1e-3"):
            aa = agg(C, ("lot", "cnn_gn", "erm", f"scratch_lr{lr}"))
            bb = agg(C, ("lot", "cnn_gn", "erm", f"sslinit_lr{lr}"))
            if aa and bb:
                lrs.append(f"{lr}: {bb['mean'] - aa['mean']:+.4f}")
        if lrs:
            W("The obvious confound — that the fine-tuning recipe was tuned for "
              "a random init — is refuted, and in the predicted direction. "
              "Sweeping both arms over learning rates, the gap *widens* as the "
              "rate falls (" + "; ".join(lrs) + "), where a recipe mismatch "
              "predicts it closing. **Rules out:** this masked-die plus "
              "gradient-reversal recipe.")
            W("")
    q = cs.get("p10_quantization")
    if q and q.get("most_common"):
        m0 = q["most_common"][0]
        W(f"**Our own `p10 domain F1` metric cannot rank models.** "
          f"{m0['n_cells']} separate `lot` cells report the identical value "
          f"{m0['value']:.6f}, and the whole set of {q['n_lot_cells']} cells "
          f"takes only {q['n_distinct_values']} distinct values. A lot holds at "
          "most 25 wafers, so a lot whose single defect is missed scores "
          "exactly (48/49 + 0)/2 whichever model missed it. The metric meant to "
          "stop a model hiding a bad tool behind a good average could not "
          "separate any two models. **Rules out:** per-lot worst-group "
          "statistics on domains this small.")
        W("")

    W("### 2.4 The forward-only result is a compound, and a quarter of it is "
      "not time")
    W("")
    tp = js("time_proxy.json")
    if tp and tp.get("split_geometry"):
        sg = tp["split_geometry"]
        W(table([[f"`{k}`", v["n_geometries_train"], v["n_geometries_test"],
                  f"{v['frac_test_wafers_unseen_geometry']:.2%}"]
                 for k, v in sg.items()],
                ["protocol", "geometries in train", "in test",
                 "test wafers of unseen geometry"]))
        W("")
    lt_rows = []
    for (p_, e, o, tg), v in sorted(C.items()):
        if o != "erm" or tg != "sess2" or p_ != "iid":
            continue
        r0 = v[sorted(v)[0]]
        lt = r0.get("test_in_lot_time_geometries")
        if not lt:
            continue
        shared = lt.get("classes_present") or []
        full = r0["test"]["per_class_f1"]
        if not shared or not all(c in full for c in shared):
            continue
        fm = sum(full[c] for c in shared) / len(shared)
        lm = sum(lt["per_class_f1"][c] for c in shared) / len(shared)
        lt_rows.append([e, f"{fm:.4f}", f"{lm:.4f}", f"{lm - fm:+.4f}"])
    if lt_rows:
        W("`lot_time` tests on a narrow geometry slice. To see whether that "
          "slice is *intrinsically* hard, score the **`iid`** models — random "
          "split, every one of those geometries seen in training, no temporal "
          "structure — on their own test wafers restricted to it:")
        W("")
        W(table(lt_rows, ["representation", "full test (matched classes)",
                          "restricted to those geometries", "cost"]))
        W("")
        W("Several points, with no time and no unseen geometry involved — many "
          "times the floor. The full `iid`-to-`lot_time` drop is about 0.18, so "
          "**roughly a quarter of it is the test set being narrow.** **Rules "
          "out:** reading `lot_time` as a measurement of temporal drift. It "
          "measures forward-only *deployment*, of which drift is one part.")
        W("")

    lb = js("label_blind.json")
    if lb:
        mx_ = max(v["max_share_in_one_lot"]
                  for v in lb["class_concentration"].values())
        W("### 2.5 One thing checked and *not* withdrawn")
        W("")
        W("Both external reviewers flagged that the group splits read candidate "
          "groups' labels. Dropping the guard entirely and comparing the "
          "partitions: it fired in "
          + ", ".join(f"{v['seeds_where_guard_fired']}/{lb['seeds']} seeds on "
                      f"`{k}`" for k, v in lb["protocols"].items())
          + ", and the partitions are identical wafer for wafer. Structurally "
            f"so — the guard rejects a group only if it holds *all* remaining "
            f"training examples of a class, and no lot holds more than "
            f"{mx_:.2%} of any class. The code path is label-aware; the split "
            "is not. This was in last revision's decision list on the strength "
            "of two reviewers agreeing; four minutes of CPU settled it.")
        W("")

    # ---------------------------------------------------------------- survives
    W("## 3. What survives the floor")
    W("")
    surv = []
    if len(P) == 3:
        mx = agg(C, ("lot", "cnn_gn", "erm", "poolmeanmax"))
        mn = agg(C, ("lot", "cnn_gn", "erm", "poolmean"))
        ctl = agg(C, ("lot", "cnn_gn", "erm", "poolmeanmean"))
        # divide by each arm's own length, not by a hardcoded 3 -- these arms
        # went from three seeds to eight and the constant stayed behind,
        # printing 8/3 of the real delta into the Monday document
        def _sc(tag):
            v = [r["test"]["per_class_f1"]["Scratch"] for r in P[tag].values()]
            return sum(v) / len(v)
        surv.append(["**Max pooling beats global average pooling**",
                     f"{mx['mean'] - mn['mean']:+.4f} macro-F1 and "
                     f"{_sc('poolmeanmax') - _sc('poolmean'):+.4f} on "
                     "`Scratch`; the capacity control gives "
                     f"{ctl['mean'] - mn['mean']:+.4f} and "
                     f"{_sc('poolmeanmean') - _sc('poolmean'):+.4f}, neither "
                     "significant at eight seeds"])
    pc = {}
    for fn in ("pooling_lot_control_perm_macro_f1.json",
               "pooling_lot_control_perm_class_Scratch.json"):
        d_ = js(fn)
        if d_:
            pc[d_["metric"]] = d_
    if not pc:
        # This row silently vanished once already, because the file it reads
        # was written with a trailing underscore and `js` returns None for a
        # missing file. A section that omits itself looks exactly like a
        # section that was never written.
        W("*(capacity-control permutation summary not found — "
          "`runs/pooling_lot_control_perm_*.json` is missing, so the row "
          "asserting the pooling gain is not extra parameters has been left "
          "out rather than silently skipped.)*")
        W("")
    if pc:
        # gn_vs_bn.py nests the p under "permutation_test"; dg_power_check.json
        # is flat. Reading the flat path here crashed the generator the moment
        # the file it wanted actually existed -- the missing filename had been
        # hiding a second bug behind the first.
        surv.append(["**The pooling gain is not extra parameters**",
                     "the capacity control at eight seeds gives "
                     + " and ".join(
                         f"{v['difference']:+.4f} on {k} "
                         f"(p = {v['permutation_test']['p_two_sided']:.3f})"
                         for k, v in sorted(pc.items()))])
    dgp = js("dg_power_check.json")
    if dgp:
        surv.append(["**Two DG objectives are worse than ERM**",
                     ", ".join(f"`{v['objective']}` {v['difference']:+.4f} "
                               f"(p = {v['p_two_sided']:.4f})"
                               for v in dgp.values())
                     + ", at eight seeds under real domains"])
    gb = js("gn_vs_bn.json")
    if gb:
        surv.append(["**GroupNorm beats BatchNorm**",
                     f"{gb['difference']:+.4f} on `lot`, permutation "
                     f"p = {gb['permutation_test']['p_two_sided']:.4f} over "
                     f"{gb['n_per_arm']} seeds per arm — the range test cannot "
                     "resolve it and never could"])
    hr = {t: agg(C, ("lot", "rpca_cnn", "erm", t))
          for t in ("hideraw2_failmask", "hideraw2_residual")}
    if all(hr.values()):
        surv.append(["The RPCA residual is a worse description of the defect "
                     "than the raw mask",
                     f"{hr['hideraw2_residual']['mean'] - hr['hideraw2_failmask']['mean']:+.4f} "
                     "when it is the *only* description; indistinguishable when "
                     "the raw mask is also present"])
    b_scr = agg(C, ("lot", "cnn_gn", "erm", ""))
    b_ssl = agg(C, ("lot", "cnn_gn", "erm", "sslinit"))
    if b_scr and b_ssl:
        surv.append(["SSL init is worse than random init",
                     f"{b_ssl['mean'] - b_scr['mean']:+.4f} on `lot`, and at "
                     "every learning rate"])
    fe, gr = agg(C, ("lot", "feat", "erm", "")), agg(C, ("lot", "graph", "erm", ""))
    if fe and gr:
        surv.append(["The die-graph GNN is last",
                     f"{gr['mean'] - fe['mean']:+.4f} against the next-worst "
                     "representation on `lot`"])
    if lt_rows:
        # the actual extremes, not the first and last rows in table order
        costs = sorted(float(r[3]) for r in lt_rows)
        surv.append(["The forward-only geometry slice is intrinsically hard",
                     f"{costs[0]:+.4f} to {costs[-1]:+.4f} on `iid`, where "
                     "nothing else differs"])
    if alw:
        surv.append(["Acquisition beats random at matched wafer budget",
                     f"+{ent_c[top_b]['macro_f1_mean'] - rnd_c[top_b]['macro_f1_mean']:.4f}"
                     f" at {Bw[-1]:,} wafers, at "
                     f"{ent_c[top_b]['lots_mean'] / rnd_c[top_b]['lots_mean']:.1f}x "
                     "the metrology slots"])
    if surv:
        W(table(surv, ["finding", "size"]))
        W("")
    W("Everything else this repository reported is inside the floor, inside the "
      "seed spread, or has no error bar at all.")
    W("")
    # ---------------------------------------------------------------- decisions
    W("## 4. Four things that need a human decision")
    W("")
    W("**Decision 1 — MixedWM38, or drop the multi-label target.** WM-811K is "
      "single-label, so \"multi-label F1\" is not defined on it. MixedWM38 "
      "could not be acquired from this machine: the HuggingFace copy "
      "(`wafervqaanon/MixedWM38-VQA`) is gated behind manual approval and "
      "Zenodo `10.5281/zenodo.20061545` returns HTTP 403 on its files. "
      "Options: **(a)** supply Kaggle credentials or request the gated copy — "
      "one human action, and the number becomes measurable on the real "
      "benchmark; **(b)** accept **MIXED-SYNTH**, built this weekend from "
      "overlaid WM-811K patterns, lot-disjoint, labelled synthetic everywhere, "
      "and report it as an upper bound; **(c)** drop the target as not well "
      "posed here. *Recommendation: (a) if anyone can spare five minutes, "
      "else (b) with the upper-bound caveat kept in front.*")
    W("")
    mx = sorted(Path(a.runs).glob("mixedsynth__*.json"))
    tgt = ""
    if mx:
        import collections as _c
        G = _c.defaultdict(list)
        for p_ in mx:
            r = json.loads(p_.read_text())
            G[(r["protocol"], r["loss"])].append(r)
        best = {}
        for proto in ("iid", "lot"):
            v = max(sum(r["test_at_val_tuned_thresholds"]["macro_f1"]
                        for r in rs) / len(rs)
                    for (pp, _l), rs in G.items() if pp == proto)
            best[proto] = v
        tgt = (f"Measured: {best['iid']:.4f} on the optimistic split and "
               f"{best['lot']:.4f} lot-disjoint, both on MIXED-SYNTH, which is "
               f"an upper bound on the real task. The shortfall is "
               f"{0.95 - best['iid']:.4f} at best. Focal's seed range overlaps "
               "plain BCE's on both protocols, so the loss named in the target "
               "contributes nothing. ")
    W("**Decision 2 — what to do about the 0.95 target, now that it is "
      "measured.** " + tgt +
      "Options: **(a)** keep the honest lot-disjoint number as the headline "
      "and make the gap to the optimistic protocol the contribution; **(b)** "
      "chase 0.95 on an iid split with augmentation and a bigger backbone, "
      "reported clearly as the optimistic protocol. *Recommendation: (a). The "
      "gap is the paper. Closing it by loosening the split is the one thing "
      "these rules forbid, and the levers that remain — backbone, pooling, "
      "real mixed-type data — are not tuning.*")
    W("")
    W("**Decision 3 — how should the forward-only result be framed?** It is "
      "the largest number here and section 2.4 shows it is a compound: a "
      "quarter of it is that the test slice is intrinsically hard, a further "
      "unmeasured share is geometries never trained on, and the rest is drift. "
      "Options: **(a)** reframe as *forward-only deployment* — a fab does meet "
      "new products going forward, so the geometry shift is part of the "
      "phenomenon rather than a confound; **(b)** build a geometry-controlled "
      "temporal protocol, isolating drift but measuring something no fab "
      "experiences; **(c)** report both. *Recommendation: (a) with the "
      "decomposition printed beside it. A fab does not get to hold its product "
      "mix fixed.*")
    W("")
    W("**Decision 4 — which acquisition cost model is real?** This is the one "
      "question here that only someone who knows the metrology contract can "
      "answer, and the two answers point opposite ways. Priced per **lot**, "
      "random acquisition wins and the heuristics waste slots on near-empty "
      "lots. Priced per **wafer measured**, entropy wins at every budget. "
      "*Recommendation: state the fab's actual cost model; both curves are "
      "already measured and reported.*")
    W("")

    # ---------------------------------------------------------------- running
    W("## 5. What is running, and how to check it")
    W("")
    W("```")
    W("tail -f logs/chain_s1.log            # stage transitions")
    W("nvidia-smi                           # devices 0,1 only; 2,3 are another loop's")
    W("ls -t runs/*.json | head             # newest cells")
    W("python scripts/report.py && python scripts/paper.py && python scripts/weekend.py")
    W("python tests/run_tests.py            # no pytest in the shared pdeno env, by design")
    W("```")
    W("")
    stages = [
        ("`repr_one_session.sh`", "logs/repr_one_session.log",
         "66 cells: every (protocol, representation) pair at three seeds, all "
         "in one session, because mixing Friday's seed 0 with this weekend's "
         "seeds 1-2 folds a session offset into what is presented as seed "
         "variance. Reported beside the original table, not replacing it"),
        ("`pooling_sweep.sh`", "logs/pooling.log",
         "**answered** (section 2.0): max pooling beats global average pooling "
         "on `lot` and the capacity control does not"),
        ("`size_objectives_seeds.sh`", "logs/size_objectives.log",
         "**answered**: nothing separates from ERM on `size` either, GroupDRO "
         "included"),
        ("`gn_vs_bn.sh`", "logs/gn_vs_bn.log",
         "**answered**: GroupNorm beats BatchNorm, permutation p = 0.011 at "
         "eight seeds per arm"),
        ("`rpca_ablation_clean.sh`", "logs/rpca_clean.log",
         "**answered**: all four fourth-channel arms within the floor of each "
         "other, as the original ablation said"),
        ("`rpca_hide_raw.sh`", "logs/rpca_hide_raw.log",
         "**answered on the second attempt**; the first was void because the "
         "one-hot planes sum to 1 and the 'hidden' plane was recoverable"),
        ("`pooling_protocols.sh`", "logs/pooling_protocols.log",
         "the only open question: does the pooling win survive `iid`, `size` "
         "and `lot_time`? Prediction on record — holds or grows on `iid`, "
         "shrinks or reverses on `lot_time`, because max pooling keeps the "
         "extreme a thin structure produces and forward-only shift is where "
         "extremes move"),
    ]
    rows = []
    for name, log, what in stages:
        p_ = Path(log)
        st = ("queued" if not p_.exists() else
              ("done" if "done ===" in p_.read_text() else "running"))
        rows.append([name, st, f"`{log}`", what])
    W(table(rows, ["stage", "status", "log", "what it decides"]))
    W("")
    W("### A property of this codebase worth knowing before you run anything")
    W("")
    W("**Its default failure mode is silence.** Four times this weekend a stage "
      "logged completion having produced nothing, or less than it claimed, and "
      "every one was found by an incidental check rather than by anything "
      "failing:")
    W("")
    W(table([
        ["`sweep_c.sh` built a log path containing a `/` from "
         "`--init-from runs/ssl_pretrain.pt`",
         "bash failed the redirect before exec; three SSL cells never ran "
         "while the sweep logged \"launch\" for each"],
        ["`report.py` keyed cells without the seed",
         "a second seed of any cell would have silently replaced the first"],
        ["the first wafer-budget acquisition run was OOM-killed",
         "its stage printed `=== al wafer budget done ===` and wrote no JSON"],
        ["`pooling_size_seeds.sh` invoked the permutation test with globs "
         "hardcoded to another protocol",
         "zero files matched; it printed a note and returned 0"],
    ], ["what happened", "what it looked like"]))
    W("")
    W("The shared shape is that **a stage boundary converts an error into an "
      "absence**, and an absence is invisible unless something counts. "
      "`scripts/verify_stage.py` is that counter — a glob and an integer, "
      "deliberately dumb, because a check that is hard to add does not get "
      "added. It is wired into the stages that end by writing a summary file, "
      "which is where three of the four failures landed. **Any new sweep should "
      "end with it.**")
    W("")
    W("The corollary for reading anything here: a missing result is not a null "
      "result. If a table says " + NM + ", check whether the run happened "
      "before concluding the effect is zero.")
    W("")
    W("The metric backfill (`scripts/backfill_metrics.sh`) is **deliberately "
      "blocked** and should stay blocked: it refuses to overwrite measured "
      "cells while a fresh re-run does not reproduce them, and overwriting the "
      "Friday cells would destroy the only record of the session offset in "
      "section 1 — which is now one of the more useful things this repository "
      "knows about itself.")
    W("")
    W("Nothing wrote outside this repository, nothing touched GPUs 2 or 3, and "
      "no package was installed into any shared environment. `runs.bak_*/` is "
      "Friday's `runs/` verbatim, gitignored, kept so any re-run can be "
      "checked against what it replaced.")
    W("")

    Path(a.out).write_text("\n".join(L) + "\n")
    print(f"wrote {a.out} from {len(C)} cells")


if __name__ == "__main__":
    main()
